services:
  openjabnab:
    build: .
    image: openjabnab:latest
    container_name: openjabnab
    restart: unless-stopped
    environment:
      - OJN_CONFIG=/config/openjabnab.ini
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/nabazgo-469413-3c3a2c9343b4.json
    volumes:
      - ./server/openjabnab.ini:/config/openjabnab.ini:ro
      - ./logs:/app/logs
      - ./secrets:/secrets:ro
    ports:
      - "8080:8080"   # HTTP bridge TCP
      - "5222:5222"   # XMPP TCP
