version: "3.9"
services:
  openjabnab:
    build: .
    ports:
      - "5222:5222"
      - "80:80"
    cap_add:
      - NET_BIND_SERVICE
    image: openjabnab:latest
    container_name: ojn-server
    restart: unless-stopped
    environment:
      - OJN_CONFIG=/config/openjabnab.ini
    volumes:
      - ./server/openjabnab.ini:/config/openjabnab.ini:ro
      - ./plugins:/config/plugins
      - ./http-wrapper:/app/http-wrapper:ro
    networks: [ojn]

networks:
  ojn:
    driver: bridge
