inline void PluginDayof::InitData()
{
    QMap<int, QMultiMap<int, QString> > data;
    QMultiMap<int, QString> data_janvier;
    QMultiMap<int, QString> data_fevrier;
    QMultiMap<int, QString> data_mars;
    QMultiMap<int, QString> data_avril;
    QMultiMap<int, QString> data_mai;
    QMultiMap<int, QString> data_juin;
    QMultiMap<int, QString> data_juillet;
    QMultiMap<int, QString> data_aout;
    QMultiMap<int, QString> data_septembre;
    QMultiMap<int, QString> data_octobre;
    QMultiMap<int, QString> data_novembre;
    QMultiMap<int, QString> data_decembre;
    data_janvier.insert(1,QString::fromUtf8(QString("Journée du domaine public").toLatin1()));
    data_janvier.insert(1,QString::fromUtf8(QString("Journée Mondiale de la Paix").toLatin1()));
    data_janvier.insert(4,QString::fromUtf8(QString("Journée mondiale du braille").toLatin1()));
    data_janvier.insert(9,QString::fromUtf8(QString("Journée mondiale de la Corse").toLatin1()));
    data_janvier.insert(13,QString::fromUtf8(QString("Journée mondiale sans pantalon").toLatin1()));
    data_janvier.insert(19,QString::fromUtf8(QString("Journée Mondiale du migrant et du réfugié").toLatin1()));
    data_janvier.insert(21,QString::fromUtf8(QString("Journée internationale des câlins").toLatin1()));
    data_janvier.insert(24,QString::fromUtf8(QString("Journée mondiale des communications sociales").toLatin1()));
    data_janvier.insert(26,QString::fromUtf8(QString("Journée Mondiale de la Douane et sur l'éthique").toLatin1()));
    data_janvier.insert(26,QString::fromUtf8(QString("Journée Mondiale des lépreux").toLatin1()));
    data_janvier.insert(27,QString::fromUtf8(QString("Journée de la mémoire de l'Holocauste et de la prévention des crimes contre l'humanité").toLatin1()));
    data_janvier.insert(28,QString::fromUtf8(QString("Journée mondiale de la protection des données").toLatin1()));
    data_fevrier.insert(2,QString::fromUtf8(QString("Journée Mondiale des Zones Humides").toLatin1()));
    data_fevrier.insert(4,QString::fromUtf8(QString("Journée Mondiale contre le cancer").toLatin1()));
    data_fevrier.insert(5,QString::fromUtf8(QString("Journée mondiale du Nutella").toLatin1()));
    data_fevrier.insert(5,QString::fromUtf8(QString("Journée mondiale pour un internet plus sur").toLatin1()));
    data_fevrier.insert(6,QString::fromUtf8(QString("Journée Mondiale sans téléphone mobile").toLatin1()));
    data_fevrier.insert(6,QString::fromUtf8(QString("Journée internationale contre les mutilations génitales").toLatin1()));
    data_fevrier.insert(11,QString::fromUtf8(QString("Journée européenne du 112").toLatin1()));
    data_fevrier.insert(11,QString::fromUtf8(QString("Journée européenne de l'épilepsie").toLatin1()));
    data_fevrier.insert(11,QString::fromUtf8(QString("Journée mondiale des malades").toLatin1()));
    data_fevrier.insert(12,QString::fromUtf8(QString("Journée Internationale des enfants soldats").toLatin1()));
    data_fevrier.insert(13,QString::fromUtf8(QString("Journée mondiale de la radio").toLatin1()));
    data_fevrier.insert(14,QString::fromUtf8(QString("Journée internationale de sensibilisation aux cardiopathies congénitales").toLatin1()));
    data_fevrier.insert(15,QString::fromUtf8(QString("Journée internationale du Syndrome d'Angelman").toLatin1()));
    data_fevrier.insert(16,QString::fromUtf8(QString("Journée Internationale du patrimoine canadien").toLatin1()));
    data_fevrier.insert(20,QString::fromUtf8(QString("Journée mondiale de la justice sociale").toLatin1()));
    data_fevrier.insert(21,QString::fromUtf8(QString("Journée Internationale de la langue maternelle").toLatin1()));
    data_fevrier.insert(22,QString::fromUtf8(QString("Journée Mondiale du Scoutisme").toLatin1()));
    data_fevrier.insert(26,QString::fromUtf8(QString("Journée Mondiale d'action contre l'ordonnance sur les brevets en Inde").toLatin1()));
    data_fevrier.insert(28,QString::fromUtf8(QString("Journée mondiale sans Facebook").toLatin1()));
    data_fevrier.insert(28,QString::fromUtf8(QString("Journée internationale des maladies rares").toLatin1()));
    data_mars.insert(1,QString::fromUtf8(QString("Journée mondiale du compliment").toLatin1()));
    data_mars.insert(4,QString::fromUtf8(QString("Journée mondiale de lutte contre l'exploitation sexuelle").toLatin1()));
    data_mars.insert(6,QString::fromUtf8(QString("Journée Internationale de la radio et de la télévision en faveur des enfants").toLatin1()));
    data_mars.insert(7,QString::fromUtf8(QString("Journée mondiale de prière").toLatin1()));
    data_mars.insert(8,QString::fromUtf8(QString("Journée Mondiale de la Femme").toLatin1()));
    data_mars.insert(11,QString::fromUtf8(QString("Journée Mondiale de la plomberie").toLatin1()));
    data_mars.insert(12,QString::fromUtf8(QString("Journée mondiale contre la censure sur internet").toLatin1()));
    data_mars.insert(13,QString::fromUtf8(QString("Journée Mondiale du rein").toLatin1()));
    data_mars.insert(13,QString::fromUtf8(QString("Journée mondiale de prière pour la Birmanie").toLatin1()));
    data_mars.insert(14,QString::fromUtf8(QString("Journée nationale de l'audition").toLatin1()));
    data_mars.insert(15,QString::fromUtf8(QString("Journée internationale de lutte contre les violences policières").toLatin1()));
    data_mars.insert(15,QString::fromUtf8(QString("Journée Internationale des droits des consommateurs").toLatin1()));
    data_mars.insert(19,QString::fromUtf8(QString("Journée mondiale d'action contre la guerre (d'occupation en Irak)").toLatin1()));
    data_mars.insert(20,QString::fromUtf8(QString("Journée Internationale de la francophonie").toLatin1()));
    data_mars.insert(20,QString::fromUtf8(QString("Journée mondiale du bonheur").toLatin1()));
    data_mars.insert(20,QString::fromUtf8(QString("Journée  Mondiale du Conte").toLatin1()));
    data_mars.insert(20,QString::fromUtf8(QString("Journée internationale sans viande").toLatin1()));
    data_mars.insert(20,QString::fromUtf8(QString("Semaine internationale pour les alternatives aux pesticides").toLatin1()));
    data_mars.insert(21,QString::fromUtf8(QString("Journée Mondiale de la Trisomie 21").toLatin1()));
    data_mars.insert(21,QString::fromUtf8(QString("Semaine nationale de lutte contre le cancer").toLatin1()));
    data_mars.insert(21,QString::fromUtf8(QString("Journée européenne de la musique ancienne").toLatin1()));
    data_mars.insert(21,QString::fromUtf8(QString("Journée mondiale de la marionnette").toLatin1()));
    data_mars.insert(21,QString::fromUtf8(QString("Journée Internationale pour l'élimination de la discrimination raciale").toLatin1()));
    data_mars.insert(21,QString::fromUtf8(QString("Journée Internationale des forêts").toLatin1()));
    data_mars.insert(21,QString::fromUtf8(QString("Journée Mondiale de la Poésie").toLatin1()));
    data_mars.insert(22,QString::fromUtf8(QString("Journée nationale du sommeil").toLatin1()));
    data_mars.insert(22,QString::fromUtf8(QString("Journée Mondiale de l'eau").toLatin1()));
    data_mars.insert(23,QString::fromUtf8(QString("Journée Mondiale de la Météorologie").toLatin1()));
    data_mars.insert(24,QString::fromUtf8(QString("Journée Mondiale de lutte contre la tuberculose").toLatin1()));
    data_mars.insert(24,QString::fromUtf8(QString("Journée nationale de la courtoisie au volant").toLatin1()));
    data_mars.insert(24,QString::fromUtf8(QString("Journée Européenne de la glace artisanale").toLatin1()));
    data_mars.insert(25,QString::fromUtf8(QString("Journée Européenne de l'enfant à naître").toLatin1()));
    data_mars.insert(25,QString::fromUtf8(QString("Journée de la procrastination").toLatin1()));
    data_mars.insert(27,QString::fromUtf8(QString("Journée nationale du fromage").toLatin1()));
    data_mars.insert(27,QString::fromUtf8(QString("Journée Mondiale du théâtre").toLatin1()));
    data_mars.insert(29,QString::fromUtf8(QString("Journée mondiale de l'allaitement").toLatin1()));
    data_avril.insert(2,QString::fromUtf8(QString("Journée mondiale de sensibilisation à l'autisme").toLatin1()));
    data_avril.insert(4,QString::fromUtf8(QString("Journée internationale de la sensibilisation au problème des mines et de l’assistance à la lutte antimines").toLatin1()));
    data_avril.insert(7,QString::fromUtf8(QString("Journée Mondiale de la santé").toLatin1()));
    data_avril.insert(7,QString::fromUtf8(QString("Journée Internationale de réflexion sur le génocide de 1994 au Rwanda").toLatin1()));
    data_avril.insert(8,QString::fromUtf8(QString("Journée internationale des Roms").toLatin1()));
    data_avril.insert(12,QString::fromUtf8(QString("Journée Mondiale de la maladie de Parkinson").toLatin1()));
    data_avril.insert(15,QString::fromUtf8(QString("Journée Mondiale de l'Art").toLatin1()));
    data_avril.insert(16,QString::fromUtf8(QString("Journée Mondiale contre l'esclavage des enfants").toLatin1()));
    data_avril.insert(16,QString::fromUtf8(QString("Journée mondiale de la voix").toLatin1()));
    data_avril.insert(17,QString::fromUtf8(QString("Journée Mondiale de l'hémophilie").toLatin1()));
    data_avril.insert(17,QString::fromUtf8(QString("Journée Mondiale des luttes paysannes").toLatin1()));
    data_avril.insert(18,QString::fromUtf8(QString("Journée internationale des monuments et des sites").toLatin1()));
    data_avril.insert(21,QString::fromUtf8(QString("Journée Mondiale de prière pour les Vocations").toLatin1()));
    data_avril.insert(22,QString::fromUtf8(QString("Journée Mondiale de la Terre").toLatin1()));
    data_avril.insert(22,QString::fromUtf8(QString("Journée Mondiale des adjointes administratives et secrétaires").toLatin1()));
    data_avril.insert(23,QString::fromUtf8(QString("Journée Mondiale du livre et du droit d'auteur").toLatin1()));
    data_avril.insert(24,QString::fromUtf8(QString("Journée Mondiale des animaux dans les laboratoires").toLatin1()));
    data_avril.insert(25,QString::fromUtf8(QString("Journée Mondiale du paludisme").toLatin1()));
    data_avril.insert(25,QString::fromUtf8(QString("Journée Mondiale pour la sauvegarde du lien parental").toLatin1()));
    data_avril.insert(26,QString::fromUtf8(QString("Journée Mondiale de la propriété intellectuelle").toLatin1()));
    data_avril.insert(28,QString::fromUtf8(QString("Journée Mondiale de la photographie au Sténopé").toLatin1()));
    data_avril.insert(28,QString::fromUtf8(QString("Journée Mondiale sur la sécurité et la santé au travail").toLatin1()));
    data_avril.insert(29,QString::fromUtf8(QString("Journée Internationale de la danse").toLatin1()));
    data_avril.insert(30,QString::fromUtf8(QString("Journée Mondiale des Mobilités et de l'Accessibilité").toLatin1()));
    data_avril.insert(30,QString::fromUtf8(QString("Journée Internationale du Jazz").toLatin1()));
    data_mai.insert(1,QString::fromUtf8(QString("Journée mondiale du travail").toLatin1()));
    data_mai.insert(3,QString::fromUtf8(QString("Journée du soleil").toLatin1()));
    data_mai.insert(3,QString::fromUtf8(QString("Journée Mondiale de la liberté de la presse").toLatin1()));
    data_mai.insert(4,QString::fromUtf8(QString("Journée Star wars").toLatin1()));
    data_mai.insert(5,QString::fromUtf8(QString("Journée Mondiale de la Sage-Femme").toLatin1()));
    data_mai.insert(5,QString::fromUtf8(QString("Journée Mondiale du rire").toLatin1()));
    data_mai.insert(6,QString::fromUtf8(QString("Journée Mondiale du coloriage").toLatin1()));
    data_mai.insert(6,QString::fromUtf8(QString("Journée Mondiale de l'asthme").toLatin1()));
    data_mai.insert(6,QString::fromUtf8(QString("Jour de l'orgue").toLatin1()));
    data_mai.insert(6,QString::fromUtf8(QString("Journée internationale sans régime").toLatin1()));
    data_mai.insert(7,QString::fromUtf8(QString("journée mondiale de sensibilisation aux passages à niveau").toLatin1()));
    data_mai.insert(7,QString::fromUtf8(QString("Journée Mondiale des orphelins du SIDA").toLatin1()));
    data_mai.insert(8,QString::fromUtf8(QString("Journée Mondiale de La Croix Rouge").toLatin1()));
    data_mai.insert(9,QString::fromUtf8(QString("Journée de l'Europe").toLatin1()));
    data_mai.insert(10,QString::fromUtf8(QString("Journée commémorative de l'abolition de l'esclavage en France métropolitaine").toLatin1()));
    data_mai.insert(10,QString::fromUtf8(QString("Journée mondiale du lupus").toLatin1()));
    data_mai.insert(11,QString::fromUtf8(QString("Journée mondiale du commerce équitable").toLatin1()));
    data_mai.insert(12,QString::fromUtf8(QString("Journée Internationale de l'infirmière").toLatin1()));
    data_mai.insert(12,QString::fromUtf8(QString("Journée Mondiale de la fibromyalgie").toLatin1()));
    data_mai.insert(13,QString::fromUtf8(QString("Journée mondiale de l'ingénierie pour l'avenir").toLatin1()));
    data_mai.insert(14,QString::fromUtf8(QString("Journée Mondiale contre l'hypertension").toLatin1()));
    data_mai.insert(15,QString::fromUtf8(QString("Journée Internationale des familles").toLatin1()));
    data_mai.insert(17,QString::fromUtf8(QString("Journée Mondiale des Télécommunications").toLatin1()));
    data_mai.insert(17,QString::fromUtf8(QString("Journée internationale contre l'homophobie").toLatin1()));
    data_mai.insert(18,QString::fromUtf8(QString("Journée Internationale des musées").toLatin1()));
    data_mai.insert(18,QString::fromUtf8(QString("Journée mondiale de la maladie coeliaque").toLatin1()));
    data_mai.insert(18,QString::fromUtf8(QString("Journée du pied").toLatin1()));
    data_mai.insert(19,QString::fromUtf8(QString("Journée Mondiale de la santé bucco-dentaire").toLatin1()));
    data_mai.insert(19,QString::fromUtf8(QString("Journée mondiale des MICI").toLatin1()));
    data_mai.insert(21,QString::fromUtf8(QString("Journée Mondiale de la diversité culturelle pour le dialogue et le développement").toLatin1()));
    data_mai.insert(22,QString::fromUtf8(QString("Journée nationale de dépistage du cancer de la peau").toLatin1()));
    data_mai.insert(22,QString::fromUtf8(QString("Journée Mondiale de la biodiversité").toLatin1()));
    data_mai.insert(22,QString::fromUtf8(QString("Journée (nationale) du marin").toLatin1()));
    data_mai.insert(23,QString::fromUtf8(QString("Journée européenne de l'obésité").toLatin1()));
    data_mai.insert(24,QString::fromUtf8(QString("Journée mondiale du rangement de bureaux").toLatin1()));
    data_mai.insert(25,QString::fromUtf8(QString("Journée Mondiale des enfants disparus").toLatin1()));
    data_mai.insert(25,QString::fromUtf8(QString("Journée internationale des Geek").toLatin1()));
    data_mai.insert(25,QString::fromUtf8(QString("Journée Mondiale de l'Afrique").toLatin1()));
    data_mai.insert(25,QString::fromUtf8(QString("Journée mondiale de la serviette").toLatin1()));
    data_mai.insert(26,QString::fromUtf8(QString("Journée mondiale de la sclérose en plaques").toLatin1()));
    data_mai.insert(26,QString::fromUtf8(QString("Journée de la fête du jeu").toLatin1()));
    data_mai.insert(27,QString::fromUtf8(QString("Semaine Nationale de sensibilisation à l'hémochromatose").toLatin1()));
    data_mai.insert(27,QString::fromUtf8(QString("Journée nationale de la résistance").toLatin1()));
    data_mai.insert(28,QString::fromUtf8(QString("Journée mondiale anti contrefaçon").toLatin1()));
    data_mai.insert(28,QString::fromUtf8(QString("Journée Internationale d'action pour la santé des femmes").toLatin1()));
    data_mai.insert(29,QString::fromUtf8(QString("Journée Internationale des casques bleus").toLatin1()));
    data_mai.insert(31,QString::fromUtf8(QString("Journée Mondiale sans tabac").toLatin1()));
    data_juin.insert(1,QString::fromUtf8(QString("Journée mondiale des parents").toLatin1()));
    data_juin.insert(2,QString::fromUtf8(QString("Journée Mondiale pour un Tourisme Responsable et Respectueux").toLatin1()));
    data_juin.insert(3,QString::fromUtf8(QString("Journée mondiale de l'orthoptique").toLatin1()));
    data_juin.insert(4,QString::fromUtf8(QString("Journée Internationale des enfants victimes innocentes d'agression").toLatin1()));
    data_juin.insert(5,QString::fromUtf8(QString("Journée Mondiale de l'environnement").toLatin1()));
    data_juin.insert(8,QString::fromUtf8(QString("Journée mondiale du tricot").toLatin1()));
    data_juin.insert(8,QString::fromUtf8(QString("Journée Mondiale des océans").toLatin1()));
    data_juin.insert(9,QString::fromUtf8(QString("Journée Internationale des Archives").toLatin1()));
    data_juin.insert(12,QString::fromUtf8(QString("Journée Mondiale contre le travail des enfants").toLatin1()));
    data_juin.insert(14,QString::fromUtf8(QString("Journée Mondiale des donneurs de sang").toLatin1()));
    data_juin.insert(15,QString::fromUtf8(QString("Journée européenne du vent (de l'énergie éolienne)").toLatin1()));
    data_juin.insert(15,QString::fromUtf8(QString("Journée Mondiale contre la Faim").toLatin1()));
    data_juin.insert(15,QString::fromUtf8(QString("Journée mondiale de lutte contre la maltraitance des personnes âgées").toLatin1()));
    data_juin.insert(16,QString::fromUtf8(QString("Journée Mondiale de l'enfant Africain").toLatin1()));
    data_juin.insert(17,QString::fromUtf8(QString("Journée Mondiale de lutte contre la désertification et la sécheresse").toLatin1()));
    data_juin.insert(19,QString::fromUtf8(QString("Journée Mondiale de la drépanocytose").toLatin1()));
    data_juin.insert(19,QString::fromUtf8(QString("Journée mondiale du naturisme").toLatin1()));
    data_juin.insert(20,QString::fromUtf8(QString("Journée Mondiale des réfugiés").toLatin1()));
    data_juin.insert(21,QString::fromUtf8(QString("Journée Mondiale de la Sclérose Latérale Amyotrophique").toLatin1()));
    data_juin.insert(21,QString::fromUtf8(QString("Journée internationale de la lenteur").toLatin1()));
    data_juin.insert(22,QString::fromUtf8(QString("Journée nationale de réflexion sur le don d'organes et la greffe").toLatin1()));
    data_juin.insert(23,QString::fromUtf8(QString("Journée mondiale des veuves").toLatin1()));
    data_juin.insert(26,QString::fromUtf8(QString("Journée Internationale contre l'abus et le trafic illicite de drogues").toLatin1()));
    data_juin.insert(26,QString::fromUtf8(QString("Journée Internationale des Nations Unies pour le soutien aux victimes de la torture").toLatin1()));
    data_juillet.insert(1,QString::fromUtf8(QString("Journée mondiale du bandeau blanc contre la pauvreté").toLatin1()));
    data_juillet.insert(6,QString::fromUtf8(QString("Journée Internationale du baiser").toLatin1()));
    data_juillet.insert(6,QString::fromUtf8(QString("Journée internationale des coopératives").toLatin1()));
    data_juillet.insert(9,QString::fromUtf8(QString("Journée de la destruction des armes légères").toLatin1()));
    data_juillet.insert(11,QString::fromUtf8(QString("Journée Mondiale de la population").toLatin1()));
    data_juillet.insert(18,QString::fromUtf8(QString("Journée internationale Nelson Mandela").toLatin1()));
    data_juillet.insert(23,QString::fromUtf8(QString("Journées mondiales de la jeunesse").toLatin1()));
    data_juillet.insert(26,QString::fromUtf8(QString("Journée Mondiale des administrateurs système").toLatin1()));
    data_juillet.insert(27,QString::fromUtf8(QString("Journée internationale du fonio").toLatin1()));
    data_juillet.insert(28,QString::fromUtf8(QString("Journée mondiale contre l'hépatite").toLatin1()));
    data_juillet.insert(30,QString::fromUtf8(QString("Journée internationale de l'amitié").toLatin1()));
    data_aout.insert(3,QString::fromUtf8(QString("Journée Mondiale du Capoeiriste").toLatin1()));
    data_aout.insert(7,QString::fromUtf8(QString("Journée Internationale de l'éducation").toLatin1()));
    data_aout.insert(8,QString::fromUtf8(QString("Journée internationale du chat").toLatin1()));
    data_aout.insert(9,QString::fromUtf8(QString("Journée Internationale des Populations autochtones").toLatin1()));
    data_aout.insert(12,QString::fromUtf8(QString("Journée Internationale de la jeunesse").toLatin1()));
    data_aout.insert(13,QString::fromUtf8(QString("Journée nationale des gauchers").toLatin1()));
    data_aout.insert(19,QString::fromUtf8(QString("Journée mondiale de la photographie").toLatin1()));
    data_aout.insert(19,QString::fromUtf8(QString("Journée mondiale de l'aide humanitaire").toLatin1()));
    data_aout.insert(23,QString::fromUtf8(QString("Journée Internationale du souvenir de la traite negrière et de son abolition").toLatin1()));
    data_aout.insert(24,QString::fromUtf8(QString("Nuit internationale de la chauve-souris").toLatin1()));
    data_aout.insert(29,QString::fromUtf8(QString("Journée Internationale contre les essais nucléaires").toLatin1()));
    data_aout.insert(30,QString::fromUtf8(QString("Journée Internationale des personnes disparues").toLatin1()));
    data_aout.insert(31,QString::fromUtf8(QString("Journée mondiale du blog").toLatin1()));
    data_septembre.insert(5,QString::fromUtf8(QString("Journée internationale de la charité").toLatin1()));
    data_septembre.insert(8,QString::fromUtf8(QString("Journée Internationale de l'alphabétisation").toLatin1()));
    data_septembre.insert(8,QString::fromUtf8(QString("Journée mondiale de la physiothérapie").toLatin1()));
    data_septembre.insert(10,QString::fromUtf8(QString("Journée Mondiale de prévention du suicide").toLatin1()));
    data_septembre.insert(11,QString::fromUtf8(QString("Journée mondiale de lutte contre le terrorisme").toLatin1()));
    data_septembre.insert(14,QString::fromUtf8(QString("Journée Mondiale des premiers secours").toLatin1()));
    data_septembre.insert(15,QString::fromUtf8(QString("Journée Internationale pour la liberté de l'instruction").toLatin1()));
    data_septembre.insert(15,QString::fromUtf8(QString("Journée mondiale du lymphome").toLatin1()));
    data_septembre.insert(15,QString::fromUtf8(QString("Journée internationale de la démocratie").toLatin1()));
    data_septembre.insert(16,QString::fromUtf8(QString("Journée Internationale de la protection de la couche d'ozone").toLatin1()));
    data_septembre.insert(18,QString::fromUtf8(QString("Journée du transport public").toLatin1()));
    data_septembre.insert(19,QString::fromUtf8(QString("Journée Internationale du Parler Pirate").toLatin1()));
    data_septembre.insert(20,QString::fromUtf8(QString("Journée Européenne de la prostate").toLatin1()));
    data_septembre.insert(21,QString::fromUtf8(QString("Journée Internationale de la paix").toLatin1()));
    data_septembre.insert(21,QString::fromUtf8(QString("Journée Mondiale de la maladie d'Alzheimer").toLatin1()));
    data_septembre.insert(22,QString::fromUtf8(QString("Journée Mondiale sans voiture").toLatin1()));
    data_septembre.insert(22,QString::fromUtf8(QString("Journee mondiale de sensibilisation à la leucémie myéloïde chronique").toLatin1()));
    data_septembre.insert(23,QString::fromUtf8(QString("Journée nationale du refus de l'échec scolaire").toLatin1()));
    data_septembre.insert(24,QString::fromUtf8(QString("Journée Mondiale contre les brevets logiciels").toLatin1()));
    data_septembre.insert(26,QString::fromUtf8(QString("Journée Européenne des langues").toLatin1()));
    data_septembre.insert(26,QString::fromUtf8(QString("Journée mondiale de la contraception").toLatin1()));
    data_septembre.insert(27,QString::fromUtf8(QString("Journée mondiale du tourisme").toLatin1()));
    data_septembre.insert(28,QString::fromUtf8(QString("Journée mondiale contre la rage").toLatin1()));
    data_septembre.insert(29,QString::fromUtf8(QString("Journée Mondiale du coeur").toLatin1()));
    data_septembre.insert(29,QString::fromUtf8(QString("Journée Mondiale des sourds").toLatin1()));
    data_septembre.insert(30,QString::fromUtf8(QString("Journée Mondiale de la mer").toLatin1()));
    data_septembre.insert(30,QString::fromUtf8(QString("Journée mondiale de la traduction").toLatin1()));
    data_octobre.insert(1,QString::fromUtf8(QString("Journée Mondiale du chocolat").toLatin1()));
    data_octobre.insert(1,QString::fromUtf8(QString("Journée Internationale de la musique").toLatin1()));
    data_octobre.insert(1,QString::fromUtf8(QString("Semaine Mondiale de l'allaitement maternel").toLatin1()));
    data_octobre.insert(1,QString::fromUtf8(QString("Journée Internationale des personnes âgées").toLatin1()));
    data_octobre.insert(2,QString::fromUtf8(QString("Journée Internationale de la non violence").toLatin1()));
    data_octobre.insert(4,QString::fromUtf8(QString("Journée nationale des aveugles et malvoyants").toLatin1()));
    data_octobre.insert(4,QString::fromUtf8(QString("Journée Mondiale des animaux").toLatin1()));
    data_octobre.insert(5,QString::fromUtf8(QString("Journée Mondiale des enseignantes et des enseignants").toLatin1()));
    data_octobre.insert(6,QString::fromUtf8(QString("Journée nationale des aidants").toLatin1()));
    data_octobre.insert(7,QString::fromUtf8(QString("Journée mondiale d'action pour le travail décent").toLatin1()));
    data_octobre.insert(7,QString::fromUtf8(QString("Journée Mondiale de l'habitat").toLatin1()));
    data_octobre.insert(9,QString::fromUtf8(QString("Journée Mondiale du handicap").toLatin1()));
    data_octobre.insert(9,QString::fromUtf8(QString("Journée Mondiale de La Poste").toLatin1()));
    data_octobre.insert(10,QString::fromUtf8(QString("Journée nationale des DYS").toLatin1()));
    data_octobre.insert(10,QString::fromUtf8(QString("Journée Mondiale contre la peine de mort").toLatin1()));
    data_octobre.insert(10,QString::fromUtf8(QString("Journée mondiale pour la vue").toLatin1()));
    data_octobre.insert(10,QString::fromUtf8(QString("Journée Mondiale de la santé mentale").toLatin1()));
    data_octobre.insert(11,QString::fromUtf8(QString("Journée Internationale du coming out").toLatin1()));
    data_octobre.insert(11,QString::fromUtf8(QString("Journée Internationale des Filles").toLatin1()));
    data_octobre.insert(11,QString::fromUtf8(QString("Journée mondiale des soins palliatifs").toLatin1()));
    data_octobre.insert(12,QString::fromUtf8(QString("Journée Internationale de la prévention des catastrophes naturelles").toLatin1()));
    data_octobre.insert(12,QString::fromUtf8(QString("Journée internationale de solidarité avec les peuples amérindiens").toLatin1()));
    data_octobre.insert(12,QString::fromUtf8(QString("Journée mondiale de l'oeuf").toLatin1()));
    data_octobre.insert(13,QString::fromUtf8(QString("Journée nationale de la sécurité routière").toLatin1()));
    data_octobre.insert(14,QString::fromUtf8(QString("Journée Mondiale pour la normalisation").toLatin1()));
    data_octobre.insert(15,QString::fromUtf8(QString("Journée Mondiale du lavage des mains").toLatin1()));
    data_octobre.insert(15,QString::fromUtf8(QString("Journée Internationale de la Canne Blanche").toLatin1()));
    data_octobre.insert(15,QString::fromUtf8(QString("Journée nationale des toxicomanies").toLatin1()));
    data_octobre.insert(15,QString::fromUtf8(QString("Journée mondiale de sensibilisation au deuil périnatal.").toLatin1()));
    data_octobre.insert(15,QString::fromUtf8(QString("Journée Internationale de la femme rurale").toLatin1()));
    data_octobre.insert(16,QString::fromUtf8(QString("Journée Mondiale de l'alimentation").toLatin1()));
    data_octobre.insert(16,QString::fromUtf8(QString("Journée mondiale du pain").toLatin1()));
    data_octobre.insert(16,QString::fromUtf8(QString("Journée nationale de dépistage de l'hépatite C").toLatin1()));
    data_octobre.insert(16,QString::fromUtf8(QString("Journée mondiale de la colonne vertébrale").toLatin1()));
    data_octobre.insert(17,QString::fromUtf8(QString("Journée Internationale pour la Résolution des Conflits").toLatin1()));
    data_octobre.insert(17,QString::fromUtf8(QString("Journée mondiale contre la douleur").toLatin1()));
    data_octobre.insert(17,QString::fromUtf8(QString("Journée mondiale du don d'organes et de la greffe").toLatin1()));
    data_octobre.insert(17,QString::fromUtf8(QString("Journée Mondiale du refus de la misère").toLatin1()));
    data_octobre.insert(18,QString::fromUtf8(QString("Journée Mondiale de la ménopause").toLatin1()));
    data_octobre.insert(18,QString::fromUtf8(QString("Journée missionnaire mondiale").toLatin1()));
    data_octobre.insert(20,QString::fromUtf8(QString("Journée Mondiale de l'ostéoporose").toLatin1()));
    data_octobre.insert(20,QString::fromUtf8(QString("Journée internationale du squash").toLatin1()));
    data_octobre.insert(20,QString::fromUtf8(QString("Journée Internationale des Cuisiniers").toLatin1()));
    data_octobre.insert(21,QString::fromUtf8(QString("Journée européenne de la dépression").toLatin1()));
    data_octobre.insert(22,QString::fromUtf8(QString("Journée Mondiale du bégaiement").toLatin1()));
    data_octobre.insert(24,QString::fromUtf8(QString("Journée Mondiale d'information sur le développement").toLatin1()));
    data_octobre.insert(24,QString::fromUtf8(QString("Journée mondiale de lutte contre la polio").toLatin1()));
    data_octobre.insert(24,QString::fromUtf8(QString("Journée des Nations Unies").toLatin1()));
    data_octobre.insert(25,QString::fromUtf8(QString("Journée Mondiale sans papier").toLatin1()));
    data_octobre.insert(26,QString::fromUtf8(QString("Journée Mondiale des pâtes").toLatin1()));
    data_octobre.insert(27,QString::fromUtf8(QString("Journée mondiale du patrimoine audiovisuel").toLatin1()));
    data_octobre.insert(28,QString::fromUtf8(QString("Journée mondiale du cinéma d'animation").toLatin1()));
    data_octobre.insert(28,QString::fromUtf8(QString("Journée Internationale de la langue et de la culture créoles").toLatin1()));
    data_octobre.insert(28,QString::fromUtf8(QString("Journée mondiale du judo").toLatin1()));
    data_octobre.insert(29,QString::fromUtf8(QString("Journée Mondiale du psoriasis").toLatin1()));
    data_octobre.insert(29,QString::fromUtf8(QString("Journée mondiale des accidents vasculaires cérébraux").toLatin1()));
    data_octobre.insert(30,QString::fromUtf8(QString("Journée mondiale de la Vie").toLatin1()));
    data_octobre.insert(31,QString::fromUtf8(QString("Journée mondiale de l'épargne").toLatin1()));
    data_novembre.insert(1,QString::fromUtf8(QString("Journée Mondiale Vegan").toLatin1()));
    data_novembre.insert(6,QString::fromUtf8(QString("Journée Internationale pour la préservation de l'environnement en temps de guerre").toLatin1()));
    data_novembre.insert(7,QString::fromUtf8(QString("Journée Internationale de l'écrivain africain").toLatin1()));
    data_novembre.insert(9,QString::fromUtf8(QString("Journée mondiale de la qualité").toLatin1()));
    data_novembre.insert(10,QString::fromUtf8(QString("Journée mondiale de sensibilisation aux tumeurs neuro-endocrines").toLatin1()));
    data_novembre.insert(10,QString::fromUtf8(QString("Journée Mondiale de la science au service de la paix et du développement").toLatin1()));
    data_novembre.insert(11,QString::fromUtf8(QString("Semaine mondiale de l'entrepreneur").toLatin1()));
    data_novembre.insert(12,QString::fromUtf8(QString("Journée Mondiale de la pneumonie").toLatin1()));
    data_novembre.insert(13,QString::fromUtf8(QString("Journée mondiale de l'utilisabilité").toLatin1()));
    data_novembre.insert(13,QString::fromUtf8(QString("Journée Mondiale de la gentillesse").toLatin1()));
    data_novembre.insert(14,QString::fromUtf8(QString("Journée mondiale du diabète").toLatin1()));
    data_novembre.insert(15,QString::fromUtf8(QString("Journée mondiale du recyclage").toLatin1()));
    data_novembre.insert(15,QString::fromUtf8(QString("Journée de la Philosophie à l'UNESCO").toLatin1()));
    data_novembre.insert(15,QString::fromUtf8(QString("Journée mondiale des écrivains en prison").toLatin1()));
    data_novembre.insert(16,QString::fromUtf8(QString("Journée Internationale de la tolérance").toLatin1()));
    data_novembre.insert(16,QString::fromUtf8(QString("Journée mondiale du souvenir des victimes des accidents de la route").toLatin1()));
    data_novembre.insert(17,QString::fromUtf8(QString("Journée Mondiale de la Prématurité").toLatin1()));
    data_novembre.insert(17,QString::fromUtf8(QString("Journée Nationale pour l'épilepsie").toLatin1()));
    data_novembre.insert(18,QString::fromUtf8(QString("Journée européenne d'information sur les antibiotiques").toLatin1()));
    data_novembre.insert(19,QString::fromUtf8(QString("Journée mondiale pour la prévention des abus envers les enfants").toLatin1()));
    data_novembre.insert(19,QString::fromUtf8(QString("Journée nationale des assistantes maternelles").toLatin1()));
    data_novembre.insert(19,QString::fromUtf8(QString("Journée Mondiale des toilettes").toLatin1()));
    data_novembre.insert(19,QString::fromUtf8(QString("Journée internationale de l'homme").toLatin1()));
    data_novembre.insert(20,QString::fromUtf8(QString("Journée internationale du souvenir trans").toLatin1()));
    data_novembre.insert(20,QString::fromUtf8(QString("Journée mondiale contre les Broncho-Pneumopathies Chroniques Obstructives").toLatin1()));
    data_novembre.insert(20,QString::fromUtf8(QString("Journée nationale de la trisomie 21").toLatin1()));
    data_novembre.insert(20,QString::fromUtf8(QString("Journée nationale contre l'herpés").toLatin1()));
    data_novembre.insert(20,QString::fromUtf8(QString("Journée Internationale des droits de l'enfant").toLatin1()));
    data_novembre.insert(20,QString::fromUtf8(QString("Journée Mondiale pour l'industrialisation de l'Afrique").toLatin1()));
    data_novembre.insert(21,QString::fromUtf8(QString("Journée Mondiale des pecheurs artisans et des travailleurs de la mer").toLatin1()));
    data_novembre.insert(21,QString::fromUtf8(QString("Journée Mondiale de la Télévision").toLatin1()));
    data_novembre.insert(22,QString::fromUtf8(QString("Journée mondiale du jeu vidéo").toLatin1()));
    data_novembre.insert(25,QString::fromUtf8(QString("Journée Internationale pour l'élimination de la violence à l'égard des femmes").toLatin1()));
    data_novembre.insert(26,QString::fromUtf8(QString("Journée internationale des aides-soignants").toLatin1()));
    data_novembre.insert(26,QString::fromUtf8(QString("Journée des enfants des rues").toLatin1()));
    data_novembre.insert(29,QString::fromUtf8(QString("Journée Internationale de solidarité avec le peuple palestinien").toLatin1()));
    data_novembre.insert(30,QString::fromUtf8(QString("Journée Mondiale Sans Achats").toLatin1()));
    data_decembre.insert(1,QString::fromUtf8(QString("Journée Mondiale de la lutte contre le SIDA").toLatin1()));
    data_decembre.insert(2,QString::fromUtf8(QString("Journée Internationale pour l'abolition de l'esclavage").toLatin1()));
    data_decembre.insert(3,QString::fromUtf8(QString("Journée Internationale des personnes handicapées").toLatin1()));
    data_decembre.insert(3,QString::fromUtf8(QString("Journée nationale du cinéma indépendant").toLatin1()));
    data_decembre.insert(5,QString::fromUtf8(QString("Journée mondiale du bénévolat").toLatin1()));
    data_decembre.insert(5,QString::fromUtf8(QString("Journée Internationale du Ninja").toLatin1()));
    data_decembre.insert(7,QString::fromUtf8(QString("Journée Internationale de l'aviation civile").toLatin1()));
    data_decembre.insert(8,QString::fromUtf8(QString("Journée mondiale du chant choral").toLatin1()));
    data_decembre.insert(8,QString::fromUtf8(QString("Journée Mondiale du Climat").toLatin1()));
    data_decembre.insert(9,QString::fromUtf8(QString("Journée Mondiale des Nations Unies contre la corruption").toLatin1()));
    data_decembre.insert(10,QString::fromUtf8(QString("Journée internationale pour les droits des animaux").toLatin1()));
    data_decembre.insert(10,QString::fromUtf8(QString("Journée Mondiale des droits de l'homme").toLatin1()));
    data_decembre.insert(11,QString::fromUtf8(QString("Journée Internationale de la montagne").toLatin1()));
    data_decembre.insert(15,QString::fromUtf8(QString("Journée [universelle] de l'esperanto").toLatin1()));
    data_decembre.insert(18,QString::fromUtf8(QString("Journée mondiale pour la langue Arabe").toLatin1()));
    data_decembre.insert(18,QString::fromUtf8(QString("Journée internationale des migrants").toLatin1()));
    data_decembre.insert(19,QString::fromUtf8(QString("Journée Internationale des Nations-Unies pour la coopération Sud-Sud").toLatin1()));
    data_decembre.insert(20,QString::fromUtf8(QString("Journée Internationale de La Solidarité Humaine").toLatin1()));
    data_decembre.insert(21,QString::fromUtf8(QString("Journée Mondiale de l'Orgasme...").toLatin1()));
    data_decembre.insert(31,QString::fromUtf8(QString("Journée mondiale vous souhaite une bonne année").toLatin1()));
    data.insert(1, data_janvier);
    data.insert(2, data_fevrier);
    data.insert(3, data_mars);
    data.insert(4, data_avril);
    data.insert(5, data_mai);
    data.insert(6, data_juin);
    data.insert(7, data_juillet);
    data.insert(8, data_aout);
    data.insert(9, data_septembre);
    data.insert(10, data_octobre);
    data.insert(11, data_novembre);
    data.insert(12, data_decembre);
}
