inline void PluginDayof::InitData()
{
  QMultiMap<int,QString> data_1;
    data_1.insert(1,"Journée Mondiale de la Paix");
    data_1.insert(4,"Journée mondiale du braille");
    data_1.insert(6,"Journée Mondiale des orphelins de guerre");
    data_1.insert(9,"Journée mondiale de la Corse");
    data_1.insert(10,"Journée mondiale Tintin");
    data_1.insert(11,"Journée du domaine public");
    data_1.insert(12,"Kiss a Ginger day*");
    data_1.insert(13,"Journée nationale de l\'hypersensibilité");
    data_1.insert(13,"Journée mondiale sans pantalon");
    data_1.insert(14,"On vous parle du Paris-Dakar");
    data_1.insert(15,"Il y a 101 ans, la Pologne renaissait de ses cendres...");
    data_1.insert(19,"Journée internationale du Pop Corn");
    data_1.insert(20,"Blue monday");
    data_1.insert(21,"Journée internationale des câlins");
    data_1.insert(22,"Journée franco-allemande");
    data_1.insert(23,"Journée mondiale des solitudes");
    data_1.insert(24,"Journée Internationale du sport féminin");
    data_1.insert(24,"Journée Internationale de l\'éducation");
    data_1.insert(25,"Journée Mondiale des lépreux");
    data_1.insert(26,"Journée Mondiale de la Douane et sur l\'éthique");
    data_1.insert(27,"Journée de la mémoire de l\'Holocauste et de la prévention des crimes contre l\'humanité");
    data_1.insert(28,"Journée mondiale de la protection des données");
  data.insert(1, data_1);
  QMultiMap<int,QString> data_2;
    data_2.insert(1,"La Journée Mondiale des intelligences animales");
    data_2.insert(2,"Journée mondiale de la vie consacrée");
    data_2.insert(2,"Journée de la marmotte");
    data_2.insert(2,"Journée Mondiale des Zones Humides");
    data_2.insert(3,"Journée internationale sans paille");
    data_2.insert(4,"Journée nationale des DIP");
    data_2.insert(4,"Journée Mondiale contre le cancer");
    data_2.insert(5,"Journée mondiale du Nutella");
    data_2.insert(6,"Journée nationale contre le terrorisme et l\'assassinat politique");
    data_2.insert(6,"Journée mondiale pour un internet plus sur");
    data_2.insert(6,"Journée internationale contre les mutilations génitales");
    data_2.insert(7,"Journée* Mondiale sans téléphone mobile");
    data_2.insert(8,"Journée mondiale de prière et de réflexion sur la traite des êtres humains");
    data_2.insert(10,"Journée internationale de l\'épilepsie");
    data_2.insert(11,"Journée mondiale des malades");
    data_2.insert(11,"Journée internationale des femmes et des filles de science");
    data_2.insert(11,"Journée européenne du 112");
    data_2.insert(12,"Journée Internationale des enfants soldats");
    data_2.insert(12,"Journée internationale Darwin");
    data_2.insert(13,"Journée mondiale de la radio");
    data_2.insert(14,"Journée internationale de sensibilisation aux cardiopathies congénitales");
    data_2.insert(15,"Journée internationale du Syndrome d\'Angelman");
    data_2.insert(15,"Journée internationale du cancer de l’enfant");
    data_2.insert(18,"Journée Internationale du patrimoine canadien");
    data_2.insert(18,"Journée mondiale d\'action en faveur du droit de grève");
    data_2.insert(19,"Journée internationale de la baleine");
    data_2.insert(20,"Journée mondiale de la justice sociale");
    data_2.insert(20,"Journée mondiale du pangolin");
    data_2.insert(21,"Journée internationale des guides touristiques");
    data_2.insert(21,"Journée Internationale de la langue maternelle");
    data_2.insert(22,"Journée Mondiale du Scoutisme");
    data_2.insert(23,"Journée mondiale pour sauver les ours");
    data_2.insert(26,"Journée Mondiale d\'action contre l\'ordonnance sur les brevets en Inde");
    data_2.insert(27,"Journée internationale de l\'ours polaire");
    data_2.insert(27,"Journée mondiale des ONG");
    data_2.insert(27,"journée mondiale de l\'anosmie");
    data_2.insert(28,"Journée mondiale sans Facebook");
    data_2.insert(29,"Journée internationale des maladies rares");
  data.insert(2, data_2);
  QMultiMap<int,QString> data_3;
    data_3.insert(1,"Journée mondiale du compliment");
    data_3.insert(1,"Journée mondiale de la protection civile");
    data_3.insert(3,"Journée mondiale de la vie sauvage");
    data_3.insert(4,"Journée mondiale de lutte contre l\'exploitation sexuelle");
    data_3.insert(4,"Journée mondiale du tennis");
    data_3.insert(4,"Journée mondiale de l\'obésité");
    data_3.insert(6,"Journée mondiale de prière");
    data_3.insert(6,"Journée Internationale de la radio et de la télévision en faveur des enfants");
    data_3.insert(6,"La journée jaune");
    data_3.insert(7,"Jour de l\'impro");
    data_3.insert(8,"Journée internationale des femmes");
    data_3.insert(9,"Journée Mondiale du rein");
    data_3.insert(10,"Semaine des mathématiques");
    data_3.insert(11,"Journée internationale des startups");
    data_3.insert(11,"Journée mondiale de la plomberie");
    data_3.insert(12,"Journée nationale de l\'audition");
    data_3.insert(12,"Journée mondiale contre la censure sur internet");
    data_3.insert(13,"Journée nationale du sommeil");
    data_3.insert(14,"Journée mondiale de la Schizophrénie");
    data_3.insert(14,"Journée internationale d\'action pour les rivières");
    data_3.insert(14,"Journée mondiale du Pi");
    data_3.insert(15,"Journée Internationale des droits des consommateurs");
    data_3.insert(15,"Grève mondiale pour le climat");
    data_3.insert(15,"Journée internationale de lutte contre les violences policières");
    data_3.insert(16,"Semaine nationale de lutte contre le cancer");
    data_3.insert(16,"Semaine internationale de la courtoisie au volant");
    data_3.insert(17,"Journée mondiale du travail social");
    data_3.insert(18,"Journée mondiale du recyclage");
    data_3.insert(20,"Journée(s) internationale(s) du livre voyageur");
    data_3.insert(20,"Journée Internationale de la francophonie");
    data_3.insert(20,"Journée  Mondiale du Conte");
    data_3.insert(20,"Journée internationale du macaron");
    data_3.insert(20,"Semaine internationale pour les alternatives aux pesticides");
    data_3.insert(20,"Journée mondiale du moineau");
    data_3.insert(20,"Journée mondiale du bonheur");
    data_3.insert(20,"Journée internationale sans viande");
    data_3.insert(20,"Journée Mondiale de la santé bucco-dentaire");
    data_3.insert(21,"Journée Mondiale de la Poésie");
    data_3.insert(21,"Journée internationale de Nowruz");
    data_3.insert(21,"Journée Mondiale de la Trisomie 21");
    data_3.insert(21,"Journée Internationale des forêts");
    data_3.insert(21,"Journée Internationale pour l\'élimination de la discrimination raciale");
    data_3.insert(21,"Journée mondiale de la marionnette");
    data_3.insert(21,"Journée mondiale du rangement de bureaux");
    data_3.insert(21,"Journée européenne de la musique ancienne");
    data_3.insert(22,"Journée Mondiale de l\'eau");
    data_3.insert(23,"Journée Mondiale de la Météorologie");
    data_3.insert(24,"Journée Mondiale de lutte contre la tuberculose");
    data_3.insert(24,"Journée Européenne de la glace artisanale");
    data_3.insert(24,"Journée mondiale pour la fin de la pêche");
    data_3.insert(24,"Journée internationale pour le droit à la vérité");
    data_3.insert(25,"Tolkien reading day");
    data_3.insert(25,"Journée de la procrastination");
    data_3.insert(25,"Journée mondiale contre la publicité");
    data_3.insert(25,"Journée Européenne de l\'enfant à naître");
    data_3.insert(25,"Journée mondiale des transports en commun");
    data_3.insert(27,"Journée nationale du fromage");
    data_3.insert(27,"Journée Mondiale du théâtre");
    data_3.insert(28,"Journée mondiale contre l\'endométriose");
    data_3.insert(30,"Journée Mondiale des troubles bipolaires");
    data_3.insert(31,"Journée mondiale de la sauvegarde des données informatiques");
    data_3.insert(31,"Journée Internationale de la Visibilité Trans");
  data.insert(3, data_3);
  QMultiMap<int,QString> data_4;
    data_4.insert(1,"Journée internationale de la blague");
    data_4.insert(2,"Journée internaionale du livre pour enfants");
    data_4.insert(2,"Journée mondiale de sensibilisation à l\'autisme");
    data_4.insert(4,"Journée mondiale de batailles d\'oreillers");
    data_4.insert(4,"Journée internationale de la sensibilisation au problème des mines et de l\'assistance à la lutte antimines");
    data_4.insert(6,"Journée mondiale du sport pour le développement et la paix");
    data_4.insert(7,"Journée Internationale de réflexion sur le génocide de 1994 au Rwanda");
    data_4.insert(7,"Journée mondiale du travail invisible");
    data_4.insert(7,"Journée Mondiale de la santé");
    data_4.insert(8,"Journée internationale des Roms");
    data_4.insert(9,"Journée mondiale de la licorne");
    data_4.insert(11,"Journée Mondiale de la maladie de Parkinson");
    data_4.insert(12,"Journée internationale du vol spatial habité");
    data_4.insert(15,"Journée Mondiale de l\'Art");
    data_4.insert(16,"Journée mondiale de la voix");
    data_4.insert(16,"Journée Mondiale contre l\'esclavage des enfants");
    data_4.insert(16,"Journée Mondiale des adjoint(e)s administratifs (-ves) et secrétaires");
    data_4.insert(17,"Journée de la femme digitale");
    data_4.insert(17,"Journée Mondiale des luttes paysannes");
    data_4.insert(17,"Journée Mondiale de l\'hémophilie");
    data_4.insert(18,"Journée internationale des monuments et des sites");
    data_4.insert(18,"Disquaire day");
    data_4.insert(18,"Journée Mondiale du cirque");
    data_4.insert(18,"Journée mondiale des radio amateurs");
    data_4.insert(21,"Journée mondiale des poissons migrateurs");
    data_4.insert(22,"Journée Mondiale de la Terre");
    data_4.insert(23,"Journée Mondiale du livre et du droit d\'auteur");
    data_4.insert(24,"Journée Mondiale des animaux dans les laboratoires");
    data_4.insert(24,"Fashion  Revolution Day");
    data_4.insert(25,"Journée Mondiale du paludisme");
    data_4.insert(25,"Journée Mondiale des Manchots");
    data_4.insert(25,"Journée Mondiale pour la sauvegarde du lien parental");
    data_4.insert(26,"Journée nationale des véhicules d\'époque");
    data_4.insert(26,"Journée Mondiale de la propriété intellectuelle");
    data_4.insert(28,"Journée Mondiale sur la sécurité et la santé au travail");
    data_4.insert(29,"Journée Mondiale de la photographie au Sténopé");
    data_4.insert(29,"Journée Internationale de la danse");
    data_4.insert(30,"Journée Mondiale des Mobilités et de l\'Accessibilité");
    data_4.insert(30,"Journée Internationale du Jazz");
    data_4.insert(30,"Journée de la non-violence éducative");
  data.insert(4, data_4);
  QMultiMap<int,QString> data_5;
    data_5.insert(1,"Journée mondiale du travail");
    data_5.insert(2,"Journée Internationale de la cuisine italienne");
    data_5.insert(2,"Journée mondiale du scrapbooking");
    data_5.insert(3,"Journée Mondiale de la liberté de la presse");
    data_5.insert(3,"Journée du soleil");
    data_5.insert(4,"Journée internationale des pompiers");
    data_5.insert(4,"Journée mondiale du jardinage nu");
    data_5.insert(4,"Journée Star wars");
    data_5.insert(5,"Journée Mondiale du rire");
    data_5.insert(5,"Journée Internationale de la Fête des Mères endeuillées");
    data_5.insert(5,"Journée internationale des drones");
    data_5.insert(5,"Journée Mondiale de l\'asthme");
    data_5.insert(5,"Journée Mondiale de la Sage-Femme");
    data_5.insert(5,"Journée du Patrimoine mondial Africain");
    data_5.insert(6,"Journée internationale sans régime");
    data_5.insert(6,"Journée Mondiale du coloriage");
    data_5.insert(7,"Journée Mondiale des orphelins du SIDA");
    data_5.insert(8,"Journée Mondiale de La Croix Rouge");
    data_5.insert(8,"Journées du souvenir et de la réconciliation en l\'honneur des morts de la Seconde Guerre mondiale");
    data_5.insert(9,"Journée de l\'Europe");
    data_5.insert(10,"Journée mondiale du lupus");
    data_5.insert(10,"Journée commémorative de l\'abolition de l\'esclavage en France métropolitaine");
    data_5.insert(11,"Journée mondiale des éspèces menacées");
    data_5.insert(11,"Journée mondiale du sandwich");
    data_5.insert(11,"Journée mondiale du commerce équitable");
    data_5.insert(12,"Journée Internationale de l\'infirmière");
    data_5.insert(12,"Jour de l\'orgue");
    data_5.insert(12,"Journée Mondiale de la fibromyalgie");
    data_5.insert(12,"Journée Mondiale de prière pour les Vocations");
    data_5.insert(13,"Journée mondiale de l\'ingénierie pour l\'avenir");
    data_5.insert(15,"Journée mondiale de la maladie coeliaque");
    data_5.insert(15,"Journée Internationale des familles");
    data_5.insert(16,"Journée internationale du vivre ensemble");
    data_5.insert(16,"Journée internationale de la lumière");
    data_5.insert(17,"Journée internationale contre l\'homophobie");
    data_5.insert(17,"Journée Mondiale des Télécommunications");
    data_5.insert(17,"Journée Mondiale contre l\'hypertension");
    data_5.insert(18,"Journée Internationale des musées");
    data_5.insert(19,"Journée mondiale des MICI");
    data_5.insert(20,"Semaine nationale de dépistage du cancer de la peau");
    data_5.insert(20,"Journée mondiale de la métrologie");
    data_5.insert(20,"Journée mondiale des abeilles");
    data_5.insert(20,"Journée européenne de la mer");
    data_5.insert(21,"Journée Mondiale de la diversité culturelle pour le dialogue et le développement");
    data_5.insert(22,"Journée Mondiale de la biodiversité");
    data_5.insert(23,"Journée mondiale de la tortue");
    data_5.insert(23,"Journée (nationale) du marin");
    data_5.insert(24,"Journée mondiale du bricolage");
    data_5.insert(25,"Journée mondiale de la serviette");
    data_5.insert(25,"Journée mondiale de la thyroïde");
    data_5.insert(25,"Journée Mondiale de l\'Afrique");
    data_5.insert(25,"Journée internationale des Geek");
    data_5.insert(25,"Journée Mondiale des enfants disparus");
    data_5.insert(27,"Journée nationale de la résistance");
    data_5.insert(28,"Journée Internationale d\'action pour la santé des femmes");
    data_5.insert(28,"Journée mondiale de l\'hygiène menstruelle");
    data_5.insert(29,"Journée Internationale des casques bleus");
    data_5.insert(30,"Journée mondiale de la sclérose en plaques");
    data_5.insert(30,"Semaine Européenne du développement durable");
    data_5.insert(30,"Journée mondiale pour le droit aux origines");
    data_5.insert(31,"Fête mondiale du jeu");
    data_5.insert(31,"Journée Mondiale sans tabac");
  data.insert(5, data_5);
  QMultiMap<int,QString> data_6;
    data_6.insert(1,"Journée mondiale du lait");
    data_6.insert(1,"Journée mondiale des parents");
    data_6.insert(2,"Journée mondiale des communications sociales");
    data_6.insert(2,"Journée Mondiale pour un Tourisme Responsable et Respectueux");
    data_6.insert(3,"Journée mondiale pour le vélo");
    data_6.insert(4,"Journée Internationale des enfants victimes innocentes d\'agression");
    data_6.insert(4,"Semaine Nationale de sensibilisation à l\'hémochromatose");
    data_6.insert(5,"Journée mondiale de la course à pieds");
    data_6.insert(5,"Journée Mondiale de l\'environnement");
    data_6.insert(6,"Journée nationale de l\'agriculture");
    data_6.insert(6,"Journée mondiale de la maladie de Verneuil");
    data_6.insert(6,"Journée de la mini-jupe");
    data_6.insert(6,"journée mondiale de sensibilisation aux passages à niveau");
    data_6.insert(6,"Journée mondiale anti contrefaçon");
    data_6.insert(6,"Journée mondiale de l\'orthoptique");
    data_6.insert(7,"Journée nationale du donut");
    data_6.insert(8,"Journée Mondiale des océans");
    data_6.insert(8,"Journée mondiale du tricot");
    data_6.insert(9,"Journée mondiale du bien-être");
    data_6.insert(9,"Journée mondiale de la santé du pied");
    data_6.insert(9,"Journée Internationale des Archives");
    data_6.insert(12,"Journée internationale de la NASH");
    data_6.insert(12,"Journée Mondiale contre le travail des enfants");
    data_6.insert(13,"Journée internationale de sensibilisation à l\'albinisme");
    data_6.insert(13,"La Nuit du handicap");
    data_6.insert(14,"Journée Mondiale des donneurs de sang");
    data_6.insert(14,"Journée mondiale de la poupée");
    data_6.insert(15,"Journée Mondiale contre la Faim");
    data_6.insert(15,"Journée européenne du vent (de l\'énergie éolienne)");
    data_6.insert(15,"Journée mondiale de lutte contre la maltraitance des personnes âgées");
    data_6.insert(15,"Journée internationale du deux roues");
    data_6.insert(16,"Journée Mondiale de l\'enfant Africain");
    data_6.insert(17,"Journée Mondiale de lutte contre la désertification et la sécheresse");
    data_6.insert(19,"Journée Mondiale de la drépanocytose");
    data_6.insert(19,"journée internationale pour l\'élimination de la violence sexuelle en temps de conflit");
    data_6.insert(20,"Journée Mondiale des réfugiés");
    data_6.insert(20,"Journée internationale du surf");
    data_6.insert(21,"Journée internationale de la lenteur");
    data_6.insert(21,"Journée Mondiale du yoga");
    data_6.insert(21,"Journée Mondiale de la Sclérose Latérale Amyotrophique");
    data_6.insert(22,"Journée nationale de réflexion sur le don d\'organes et la greffe");
    data_6.insert(23,"Journée mondiale des veuves");
    data_6.insert(23,"Journée olympique mondiale");
    data_6.insert(23,"Journée mondiale pour la fonction publique");
    data_6.insert(24,"Journée mondiale des amoureux de l\'Alsace");
    data_6.insert(25,"Journée mondiale du vitiligo");
    data_6.insert(26,"Journée Internationale contre l\'abus et le trafic illicite de drogues");
    data_6.insert(26,"Journée Internationale des Nations Unies pour le soutien aux victimes de la torture");
    data_6.insert(27,"Journée Mondiale contre l\'abandon des animaux de compagnie");
    data_6.insert(29,"Journée mondiale du Petit Prince");
    data_6.insert(30,"Journée mondiale des motards");
    data_6.insert(30,"Journée mondiale des astéroïdes");
  data.insert(6, data_6);
  QMultiMap<int,QString> data_7;
    data_7.insert(1,"Journée mondiale du naturisme");
    data_7.insert(1,"Journée mondiale du bandeau blanc contre la pauvreté");
    data_7.insert(1,"Journée internationale des coopératives");
    data_7.insert(1,"Journée mondiale du reggae");
    data_7.insert(2,"Journée mondiale des OVNI");
    data_7.insert(3,"Journée mondiale sans sacs plastique");
    data_7.insert(6,"Journée Internationale du baiser");
    data_7.insert(8,"Journée nationale des ambulanciers");
    data_7.insert(9,"Journée de la destruction des armes légères");
    data_7.insert(10,"Journée mondiale des \"femmes sans voiles\"");
    data_7.insert(11,"Journée Mondiale de la population");
    data_7.insert(12,"Journée mondiale des footballeurs pauvres");
    data_7.insert(15,"Journée internationale des jeux vidéos");
    data_7.insert(16,"Journée mondiale des serpents");
    data_7.insert(17,"Journée mondiale de la justice internationale");
    data_7.insert(17,"Journée mondiale des émojis");
    data_7.insert(18,"Journée internationale Nelson Mandela");
    data_7.insert(19,"Journée Internationale des châteaux");
    data_7.insert(21,"Journée mondiale de la malbouffe");
    data_7.insert(23,"Journée mondiale des dauphins");
    data_7.insert(26,"Journée Mondiale des administrateurs système");
    data_7.insert(26,"Journées mondiales de la jeunesse");
    data_7.insert(26,"journée internationale pour la  conservation  de l’écosystème  des  mangroves");
    data_7.insert(27,"Journée internationale du fonio");
    data_7.insert(28,"Journée mondiale contre l\'hépatite");
    data_7.insert(29,"Journée nationale du rouge à lèvres");
    data_7.insert(29,"Journée internationale du tigre");
    data_7.insert(30,"Journée mondiale de la dignité des victimes de la traite d’êtres humains");
    data_7.insert(30,"Journée internationale de l\'amitié");
    data_7.insert(31,"Journée internationale de la femme africaine");
  data.insert(7, data_7);
  QMultiMap<int,QString> data_8;
    data_8.insert(1,"Semaine Mondiale de l\'allaitement maternel");
    data_8.insert(1,"Journée internationale de la frite belge");
    data_8.insert(2,"Journée mondiale de la bière");
    data_8.insert(3,"Journée Mondiale du Capoeiriste");
    data_8.insert(8,"Journée internationale du chat");
    data_8.insert(9,"Journée mondiale de la Salsa");
    data_8.insert(9,"Journée Internationale des Populations autochtones");
    data_8.insert(10,"Journée mondiale du lion");
    data_8.insert(11,"Journée internationale des e-mails");
    data_8.insert(12,"Journée Internationale de la jeunesse");
    data_8.insert(12,"Journée mondiale des éléphants");
    data_8.insert(13,"Journée internationale des gauchers");
    data_8.insert(16,"Journée mondiale du cerf-volant");
    data_8.insert(17,"Journée internationale du géocaching");
    data_8.insert(17,"Journée internationale du chat noir");
    data_8.insert(19,"Journée mondiale de l\'aide humanitaire");
    data_8.insert(19,"Journée mondiale de la photographie");
    data_8.insert(21,"Journée Internationale du souvenir en hommage aux victimes du terrorisme");
    data_8.insert(22,"Journée internationale de commémoration des personnes victimes  de violences en raison de leur religion ou convictions");
    data_8.insert(23,"Journée Internationale du souvenir de la traite negrière et de son abolition");
    data_8.insert(24,"Journée internationale de sensibilisation aux vautours");
    data_8.insert(25,"Journée mondiale pour la fin du spécisme");
    data_8.insert(26,"Journée mondiale Topless");
    data_8.insert(26,"Journée mondiale du chien");
    data_8.insert(29,"Journée Internationale contre les essais nucléaires");
    data_8.insert(30,"Journée Internationale des personnes disparues");
    data_8.insert(31,"Nuit internationale de la chauve-souris");
    data_8.insert(31,"Journée internationale de prévention des overdoses");
    data_8.insert(31,"Journée mondiale du blog");
  data.insert(8, data_8);
  QMultiMap<int,QString> data_9;
    data_9.insert(1,"Journée mondiale de prière pour la Création");
    data_9.insert(2,"Notre nouveau site va être publié dans la semaine");
    data_9.insert(3,"On vous parle de la nouvelle version du site Journée Mondiale");
    data_9.insert(4,"On vous parle de l\'anniversaire de Google");
    data_9.insert(5,"Journée internationale de la charité");
    data_9.insert(5,"Journée internationale du Blessé Médullaire");
    data_9.insert(6,"le Festival du Cinéma Américain de Deauville");
    data_9.insert(7,"Journée mondiale de la myopathie de Duchenne");
    data_9.insert(7,"Journée mondiale de la barbe");
    data_9.insert(8,"Journée mondiale de la physiothérapie");
    data_9.insert(8,"Journée Internationale de l\'alphabétisation");
    data_9.insert(9,"Journée mondiale de la peluche...");
    data_9.insert(9,"Journée mondiale de sensibilisation au syndrome d’alcoolisation fœtale");
    data_9.insert(10,"Journée Mondiale de prévention du suicide");
    data_9.insert(11,"Journée mondiale de lutte contre le terrorisme");
    data_9.insert(12,"Journée Internationale des Nations-Unies pour la coopération Sud-Sud");
    data_9.insert(13,"Journée Mondiale des programmeurs et développeurs");
    data_9.insert(13,"Journée Mondiale contre la Septicémie");
    data_9.insert(14,"Journée Mondiale des premiers secours");
    data_9.insert(15,"Journée Internationale pour la liberté de l\'instruction");
    data_9.insert(15,"Journée internationale de la démocratie");
    data_9.insert(15,"Journée mondiale du lymphome");
    data_9.insert(16,"Journée Internationale de la protection de la couche d\'ozone");
    data_9.insert(17,"Semaine européenne de la mobilité");
    data_9.insert(17,"Journée Mondiale de l\'Arthrose");
    data_9.insert(18,"Journée nationale de la qualité de l\'air");
    data_9.insert(19,"Journée Internationale du Parler Pirate");
    data_9.insert(19,"Journée Européenne de la psychomotricité");
    data_9.insert(19,"Journée mondiale du nettoyage");
    data_9.insert(20,"Journée internationale du sport universitaire");
    data_9.insert(20,"Journée Européenne de la prostate");
    data_9.insert(20,"Journée mondiale du logiciel libre");
    data_9.insert(21,"Journée Mondiale de la maladie d\'Alzheimer");
    data_9.insert(21,"Journée européenne des initiatives citoyennes de transition");
    data_9.insert(21,"Journée Internationale de la paix");
    data_9.insert(21,"Journée internationale de la bibliodiversité");
    data_9.insert(21,"Journées européennes du patrimoine");
    data_9.insert(21,"Journée du transport public");
    data_9.insert(22,"Journée Mondiale sans voiture");
    data_9.insert(22,"Journee mondiale de sensibilisation à la leucémie myéloïde chronique");
    data_9.insert(22,"Journée mondiale du rhinocéros");
    data_9.insert(23,"journée internationale de la maladie de Willis-Ekbom");
    data_9.insert(23,"Journée de la bisexualité");
    data_9.insert(23,"Journée nationale du refus de l\'échec scolaire");
    data_9.insert(24,"Journée Mondiale contre les brevets logiciels");
    data_9.insert(25,"Nuit européenne des chercheurs");
    data_9.insert(26,"Journée mondiale de la contraception");
    data_9.insert(26,"Journée des grands parents");
    data_9.insert(26,"Journée Mondiale de la mer");
    data_9.insert(26,"Journée Européenne des langues");
    data_9.insert(27,"Journées internationales de la Gastronomie");
    data_9.insert(27,"Journée mondiale du tourisme");
    data_9.insert(28,"Journée mondiale du droit à l\'avortement");
    data_9.insert(28,"Journée mondiale contre la rage");
    data_9.insert(28,"Journée Mondiale des sourds");
    data_9.insert(28,"Journée Internationale du droit d\'accès à l\'information");
    data_9.insert(29,"Journée Mondiale du coeur");
    data_9.insert(29,"Journée Mondiale du migrant et du réfugié");
    data_9.insert(30,"Journée mondiale de la traduction");
  data.insert(9, data_9);
  QMultiMap<int,QString> data_10;
    data_10.insert(1,"Journée Internationale de la musique");
    data_10.insert(1,"Journée Mondiale du chocolat");
    data_10.insert(1,"Journée mondiale du végétarisme");
    data_10.insert(1,"Journée mondiale de l\'urticaire");
    data_10.insert(1,"Journée internationale du café");
    data_10.insert(1,"Journée Internationale des personnes âgées");
    data_10.insert(2,"Journée Internationale de la non violence");
    data_10.insert(3,"Comme c\'est la Saint Gérard, on vous parle des Gérard d\'or");
    data_10.insert(4,"Journée mondiale du sourire");
    data_10.insert(4,"Journée nationale des aveugles et malvoyants");
    data_10.insert(4,"Journée Mondiale des animaux");
    data_10.insert(5,"Journée nationale de la marche nordique");
    data_10.insert(5,"Journée Mondiale des enseignantes et des enseignants");
    data_10.insert(6,"Journée nationale des aidants");
    data_10.insert(6,"Journée mondiale de la paralysie cérébrale");
    data_10.insert(7,"Journée mondiale d\'action pour le travail décent");
    data_10.insert(7,"Journée Mondiale de l\'habitat");
    data_10.insert(7,"Journée mondiale de l\'architecture");
    data_10.insert(8,"on parle de la grève dans le monde de la santé");
    data_10.insert(9,"Journée Mondiale de La Poste");
    data_10.insert(9,"Journée Mondiale du handicap");
    data_10.insert(10,"Journée internationale de l\'X fragile");
    data_10.insert(10,"Journée Mondiale contre la peine de mort");
    data_10.insert(10,"Journée mondiale pour la vue");
    data_10.insert(10,"Journée Mondiale de la santé mentale");
    data_10.insert(10,"Journée nationale des DYS");
    data_10.insert(11,"Journée Internationale des Filles");
    data_10.insert(11,"Journée Internationale du coming out");
    data_10.insert(12,"Journée mondiale de l\'arthrite");
    data_10.insert(12,"Journée mondiale des soins palliatifs");
    data_10.insert(12,"Journée internationale de solidarité avec les peuples amérindiens");
    data_10.insert(13,"Journée mondiale de l\'oeuf");
    data_10.insert(13,"Journée Internationale de la prévention des catastrophes naturelles");
    data_10.insert(13,"Journée nationale de la sécurité routière");
    data_10.insert(13,"Journée internationale du hamburger");
    data_10.insert(14,"Journée Mondiale pour la normalisation");
    data_10.insert(14,"Jour de Christophe Colomb");
    data_10.insert(15,"Journée Internationale de la Canne Blanche");
    data_10.insert(15,"Journée Mondiale du lavage des mains");
    data_10.insert(15,"Journée Internationale de la femme rurale");
    data_10.insert(15,"Journée internationale des fossiles");
    data_10.insert(15,"Journée nationale des toxicomanies");
    data_10.insert(15,"Journée mondiale de sensibilisation au deuil périnatal.");
    data_10.insert(16,"Journée mondiale de la colonne vertébrale");
    data_10.insert(16,"Journée Mondiale de l\'alimentation");
    data_10.insert(16,"Journée mondiale du pain");
    data_10.insert(17,"Journée mondiale du don d\'organes et de la greffe");
    data_10.insert(17,"Journée Mondiale du refus de la misère");
    data_10.insert(18,"Journée Mondiale de la ménopause");
    data_10.insert(18,"Journée Internationale pour la Résolution des Conflits");
    data_10.insert(18,"Journée mondiale du Champagne (Champagne\' Day)");
    data_10.insert(19,"la loi sur les 35 heures a 20 ans");
    data_10.insert(20,"Journée missionnaire mondiale");
    data_10.insert(20,"Journée internationale du squash");
    data_10.insert(20,"Journée mondiale de la statistique");
    data_10.insert(20,"Journée Internationale des Cuisiniers");
    data_10.insert(20,"Journée Mondiale de l\'ostéoporose");
    data_10.insert(21,"Journée mondiale contre la douleur");
    data_10.insert(22,"Journée mondiale de l\'énergie");
    data_10.insert(22,"Journée Mondiale du bégaiement");
    data_10.insert(23,"Le peuple Hongrois se soulève pour la liberté");
    data_10.insert(24,"Journée mondiale de lutte contre la polio");
    data_10.insert(24,"Journée des Nations Unies");
    data_10.insert(24,"Journée Mondiale d\'information sur le développement");
    data_10.insert(25,"Journée Mondiale des pâtes");
    data_10.insert(25,"Journée européenne de la justice");
    data_10.insert(26,"on peut toujours en profiter pour passer du bon temps avec ses amis");
    data_10.insert(27,"Journée européenne de la dépression");
    data_10.insert(27,"Journée mondiale du patrimoine audiovisuel");
    data_10.insert(27,"Journée mondiale de l\'ergothérapie");
    data_10.insert(28,"Journée Internationale de la langue et de la culture créoles");
    data_10.insert(28,"Journée mondiale du cinéma d\'animation");
    data_10.insert(28,"Journée mondiale du judo");
    data_10.insert(29,"Journée mondiale des accidents vasculaires cérébraux");
    data_10.insert(29,"Journée Mondiale du psoriasis");
    data_10.insert(30,"Journée mondiale de la Vie");
    data_10.insert(31,"Journée mondiale de l\'épargne");
  data.insert(10, data_10);
  QMultiMap<int,QString> data_11;
    data_11.insert(1,"Journée Mondiale Vegan");
    data_11.insert(2,"Journée internationale de la fin de l’impunité pour les crimes commis contre des journalistes");
    data_11.insert(3,"Journée Mondiale de la gentillesse");
    data_11.insert(4,"Journée annuelle des parents au bureau");
    data_11.insert(5,"Journée mondiale de la langue Romani");
    data_11.insert(5,"Journée mondiale de sensibilisation aux tsunamis");
    data_11.insert(6,"Journée Internationale pour la préservation de l\'environnement en temps de guerre");
    data_11.insert(6,"Journée Mondiale sans papier");
    data_11.insert(7,"Journée mondiale de la qualité");
    data_11.insert(7,"Journée nationale de lutte contre le harcèlement scolaire");
    data_11.insert(7,"Journée Internationale de l\'écrivain africain");
    data_11.insert(8,"Journée internationale de la radiologie");
    data_11.insert(9,"C\'est l\'anniversaire de la chute du Mur de Berlin");
    data_11.insert(10,"Journée internationale des stagiaires");
    data_11.insert(10,"Journée Mondiale de la science au service de la paix et du développement");
    data_11.insert(10,"Journée mondiale du kératocône");
    data_11.insert(10,"Journée mondiale de sensibilisation aux tumeurs neuro-endocrines");
    data_11.insert(11,"Journée internationale des célibataires");
    data_11.insert(12,"Journée Mondiale de la pneumonie");
    data_11.insert(13,"Journée internationale des GIS (systèmes d\'information géographiques)");
    data_11.insert(13,"Journée mondiale de la vasectomie");
    data_11.insert(14,"Journée mondiale du diabète");
    data_11.insert(14,"Journée mondiale de l\'utilisabilité");
    data_11.insert(15,"Journée mondiale des écrivains en prison");
    data_11.insert(16,"Semaine européenne de réduction des déchets");
    data_11.insert(16,"Journée Internationale de la tolérance");
    data_11.insert(17,"Journée mondiale du souvenir des victimes des accidents de la route");
    data_11.insert(17,"Journée mondiale des pauvres");
    data_11.insert(17,"Journée nationale de la trisomie 21");
    data_11.insert(17,"Journée Mondiale de la Prématurité");
    data_11.insert(18,"Journée européenne d\'information sur les antibiotiques");
    data_11.insert(18,"Semaine mondiale de l\'entrepreneur");
    data_11.insert(19,"Journée Mondiale des toilettes");
    data_11.insert(19,"Journée internationale de l\'homme");
    data_11.insert(19,"Journée nationale des assistantes maternelles");
    data_11.insert(19,"Journée mondiale pour la prévention des abus envers les enfants");
    data_11.insert(20,"Journée Mondiale pour l\'industrialisation de l\'Afrique");
    data_11.insert(20,"Journée nationale contre l\'herpés");
    data_11.insert(20,"Journée internationale du souvenir trans");
    data_11.insert(20,"Journée Internationale des droits de l\'enfant");
    data_11.insert(21,"Journée Mondiale des pecheurs artisans et des travailleurs de la mer");
    data_11.insert(21,"Journée Mondiale de la Télévision");
    data_11.insert(21,"Journée de la Philosophie à l\'UNESCO");
    data_11.insert(21,"Journée mondiale contre les Broncho-Pneumopathies Chroniques Obstructives");
    data_11.insert(22,"Journée mondiale du jeu vidéo");
    data_11.insert(23,"Journée Mondiale Sans Achats");
    data_11.insert(24,"Journée internationale de la Bible");
    data_11.insert(25,"Journée Internationale pour l\'élimination de la violence à l\'égard des femmes");
    data_11.insert(25,"Journée mondiale anti foie gras");
    data_11.insert(26,"Journée internationale des aides-soignants");
    data_11.insert(26,"Journée des enfants des rues");
    data_11.insert(27,"Patientez un peu, demain il va y avoir du sport !");
    data_11.insert(28,"Mais on se prépare à célébrer Thanksgiving. Et demain, c\'est le Black Friday....");
    data_11.insert(29,"Journée Internationale de solidarité avec le peuple palestinien");
  data.insert(11, data_11);
  QMultiMap<int,QString> data_12;
    data_12.insert(1,"Journée Mondiale de la lutte contre le SIDA");
    data_12.insert(2,"Journée Internationale pour l\'abolition de l\'esclavage");
    data_12.insert(2,"Journée internationale de la samba");
    data_12.insert(3,"Journée nationale du cinéma indépendant");
    data_12.insert(3,"Journée Internationale des personnes handicapées");
    data_12.insert(3,"Journée mondiale de la générosité");
    data_12.insert(5,"Journée Mondiale de l\'égalité des chances");
    data_12.insert(5,"Journée mondiale des sols");
    data_12.insert(5,"Journée Internationale du Ninja");
    data_12.insert(5,"Journée mondiale du bénévolat");
    data_12.insert(6,"journée française de la maladie d\'Huntington");
    data_12.insert(7,"Journée Internationale de l\'aviation civile");
    data_12.insert(8,"Journée Mondiale du Climat");
    data_12.insert(8,"Journée mondiale des enfants partis trop tôt.");
    data_12.insert(8,"Journée mondiale du chant choral");
    data_12.insert(9,"Journée Mondiale des Nations Unies contre la corruption");
    data_12.insert(9,"Journée nationale de la laïcité");
    data_12.insert(9,"Journée internationale de prévention des génocides");
    data_12.insert(10,"Journée internationale pour les droits des animaux");
    data_12.insert(10,"Journée Mondiale des droits de l\'homme");
    data_12.insert(11,"Journée Internationale de la montagne");
    data_12.insert(12,"Journée internationale de la musique  Metal");
    data_12.insert(13,"vous avez de la chance, c\'est un vendredi 13");
    data_12.insert(15,"Journée internationale du thé");
    data_12.insert(15,"Journée mondiale des Otakus");
    data_12.insert(15,"Journée [universelle] de l\'esperanto");
    data_12.insert(18,"Journée internationale des migrants");
    data_12.insert(18,"Journée mondiale pour la langue Arabe");
    data_12.insert(20,"Journée mondiale de l\'humanisme");
    data_12.insert(20,"Journée internationale du pull de Noël");
    data_12.insert(20,"Journée Internationale de La Solidarité Humaine");
    data_12.insert(21,"Journée Mondiale de l\'Orgasme...");
    data_12.insert(25,"c\'est pas une raison pour ne pas souhaiter un Joyeux Noël !");
    data_12.insert(26,"C\'est le jour des boites...");
    data_12.insert(30,"On en profite pour répondre à une question parfois posée...");
    data_12.insert(31,"Journée mondiale vous souhaite une bonne année 2020");
  data.insert(12, data_12);
}
