cmake_minimum_required(VERSION 3.7)

add_subdirectory(dice/)
add_subdirectory(dico/)
add_subdirectory(ears/)
add_subdirectory(fairytales/)
add_subdirectory(lafontaine/)
add_subdirectory(memo/)
add_subdirectory(music/)
add_subdirectory(nab2nab/)
#add_subdirectory(nabcast/)
add_subdirectory(rss/)
add_subdirectory(webradio/)

