cmake_minimum_required(VERSION 3.7)
project(ojn)


add_library(${PROJECT_NAME} SHARED
#WIN32
dbmanager.h
QsLog.h
QsLogDest.h
QsLogDestFile.h
QsLogDestConsole.h
sentencemanager.h
timezonemanager.h
timezone.h
translator.h
httphandler.h
nabaztagmanager.h
xmpphandler.h
httprequest.h
settings.h
#logger.h
log.h
browsercache.h
browserclient.h
pluginmanager.h
pluginapihandler.h
pluginauthinterface.h
plugininterface.h
plugininterface_inline.h
pluginmessageinterface.h
pluginmessageinterface_inline.h
packet.h
ambientpacket.h
chorconfigpacket.h
serviceconfigpacket.h
messagepacket.h
sleeppacket.h
configpacket.h
choregraphy.h
bunnymanager.h
bunny.h
ztampmanager.h
ztamp.h
apimanager.h
cron.h
voice.h
sleeptime.h
ttsanswer.h
ttsmanager.h
ttsinterface.h
ttsinterface_inline.h
accountmanager.h
account.h
apihandler.h
iq.h
dbmanager.cpp
QsLog.cpp
QsLogDest.cpp
QsLogDestFile.cpp
QsLogDestConsole.cpp
sentencemanager.cpp
timezonemanager.cpp
timezone.cpp
translator.cpp
httphandler.cpp
nabaztagmanager.cpp
xmpphandler.cpp
httprequest.cpp
settings.cpp
#logger.cpp
log.cpp
browsercache.cpp
browserclient.cpp
pluginmanager.cpp
packet.cpp
ambientpacket.cpp
chorconfigpacket.cpp
serviceconfigpacket.cpp
messagepacket.cpp
sleeppacket.cpp
configpacket.cpp
choregraphy.cpp
bunnymanager.cpp
bunny.cpp
ztampmanager.cpp
ztamp.cpp
apimanager.cpp
cron.cpp
ttsmanager.cpp
accountmanager.cpp
account.cpp
iq.cpp
)
QT5_USE_MODULES(${PROJECT_NAME} Core Network Sql)

if(WIN32)
target_compile_definitions(${PROJECT_NAME}
PUBLIC
  OJN_MAKEDLL
)
target_link_libraries(${PROJECT_NAME}
  Ws2_32
)
endif()

target_include_directories(${PROJECT_NAME}
PUBLIC
  ${CMAKE_CURRENT_SOURCE_DIR}
)
