inline void PluginDicton::InitData()
{
	QMap<int, QString> data_janvier;
	data_janvier.insert(1,"Année neigeuse, année fructueuse.");
	data_janvier.insert(2,"Au mois de janvier, mieux vaut voir le loup dans les champs, qu'un homme en chemise.");
	data_janvier.insert(3,"Beaux jours de janvier trompent l'homme en février.");
	data_janvier.insert(4,"Brouillard en janvier, année ensoleillée.");
	data_janvier.insert(5,"Brouillard en janvier, année mouillée");
	data_janvier.insert(6,"Brouillard en janvier, froid en mai");
	data_janvier.insert(7,"Cadeau de janvier, ingratitude de février.");
	data_janvier.insert(8,"Dieu te garde d'un bon janvier.");
	data_janvier.insert(9,"En janvier, le paysage n'a rien");
	data_janvier.insert(10,"Garde toi du mois de janvier comme un voleur au grenier. S'il fait vent, nous aurons la guerre, et si l'on voit épais brouillards, mortalité de toute part.");
	data_janvier.insert(11,"Garde-toi du printemps de janvier !");
	data_janvier.insert(12,"Il vaut mieux voir un voleur dans son grenier qu'un laboureur en chemise en janvier");
	data_janvier.insert(13,"janvier amasse les souches, février les brûle toutes");
	data_janvier.insert(14,"janvier d'eau chiche fait le paysan riche.");
	data_janvier.insert(15,"janvier frileux gèle la merlesse sur les oeufs.");
	data_janvier.insert(16,"janvier frileux, gèle l'oiseau sur ses oeufs.");
	data_janvier.insert(17,"janvier ne veut pas voir pisser un rat.");
	data_janvier.insert(18,"janvier sec et sage, est un bon présage.");
	data_janvier.insert(19,"janvier sec et beau, remplit cuve et tonneaux.");
	data_janvier.insert(20,"Le mauvais An entre en nageant");
	data_janvier.insert(21,"Les douze jours qui vont de Noël aux Rois, donnent le temps des douze mois.");
	data_janvier.insert(22,"Les douze premiers jours de janvier, indiquent le temps qu'il fera les douze mois de l'année.");
	data_janvier.insert(23,"Les hivers les plus froids, sont ceux qui prennent vers les Rois");
	data_janvier.insert(24,"L'or du soleil en janvier, est or que l'on ne doit envier.");
	data_janvier.insert(25,"Mi-janvier, Mi-paille");
	data_janvier.insert(26,"Mieux vaut voir chien enragé que chaud soleil en janvier (ou janvier-février)");
	data_janvier.insert(27,"Neige en janvier, blé au grenier.");
	data_janvier.insert(28,"Neige de janvier vaut fumier.");
	data_janvier.insert(29,"On a vu le plus mauvais temps quand janvier montre les dents.");
	data_janvier.insert(30,"Pluie de juillet, eau en janvier.");
	data_janvier.insert(31,"Pluie qui dure en janvier suffit pour toute l'année");
	data.insert(1, data_janvier);
	QMap<int, QString> data_fevrier;
	data_fevrier.insert(1,"A mi-février, mi-grenier");
	data_fevrier.insert(2,"Au mois de février, chaque bête cherche son pareil");
	data_fevrier.insert(3,"Au mois de février, chaque herbe fait son pied.");
	data_fevrier.insert(4,"Beau février c'est disette au grenier.");
	data_fevrier.insert(5,"Beaux jours de janvier trompent l'homme en février.");
	data_fevrier.insert(6,"Cadeau de janvier, ingratitude de février.");
	data_fevrier.insert(7,"Crapaud qui chante en février a l'Hiver derrière lui.");
	data_fevrier.insert(8,"Eau de février vaut jus de fumier (ou eau de fumier).");
	data_fevrier.insert(9,"En février, civelles, en mars, bonnes et belles, En avril, fi d'elles.");
	data_fevrier.insert(10,"En février, la feuille au groseiller.");
	data_fevrier.insert(11,"En février le tonnerre fait tenir l'huile dans une cuillére.");
	data_fevrier.insert(12,"En février, les agneaux naissent plus beaux.");
	data_fevrier.insert(13,"En février toute oie de bonne race pond sur le fumier");
	data_fevrier.insert(14,"février avec neige nous garantit un bel été");
	data_fevrier.insert(15,"février, bon mois pour semer carottes et pois.");
	data_fevrier.insert(16,"février doit remplir les fossés, et mars, après, les quitter séchés.");
	data_fevrier.insert(17,"février, entre tous les mois, le plus court et le moins courtois.");
	data_fevrier.insert(18,"février est de tous les mois, le plus court et le plus mâtois");
	data_fevrier.insert(19,"février et mars trop chauds, mettent le printemps au tombeau.");
	data_fevrier.insert(20,"février finit vite et commence bien.");
	data_fevrier.insert(21,"février, le plus court des mois, est de tous le pire à la fois.");
	data_fevrier.insert(22,"février n'a pas deux jours pareils");
	data_fevrier.insert(23,"février neigeux, Eté avantageux");
	data_fevrier.insert(24,"février n'est jamais si dur et si méchant qu'il ne nous fasse don de sept jours de printemps.");
	data_fevrier.insert(25,"février qui gèle et tonne annonce un bel automne");
	data_fevrier.insert(26,"février remplit les fossés, c'est à mars de les assécher.");
	data_fevrier.insert(27,"février remplit les fossés, mars les vide.");
	data_fevrier.insert(28,"février rigoureux effraie les frileux.");
	data.insert(2, data_fevrier);
	QMap<int, QString> data_mars;
	data_mars.insert(1,"A mars poudreux, avril pluvieux.");
	data_mars.insert(2,"Au commencement, à la fin, mars a du poison.");
	data_mars.insert(3,"Autant de brouillard en mars que de gelées en mai.");
	data_mars.insert(4,"Autant de brumes en mars, autant de fruits en mai");
	data_mars.insert(5,"Autant de gelées en mars, autant de rosées en avril.");
	data_mars.insert(6,"Brouillard en mars, gelée en mai.");
	data_mars.insert(7,"C'est en mars que le Printemps chante, et que les rhumatismes commencent (ou augmentent).");
	data_mars.insert(8,"De mars la verdure, mauvaise augure.");
	data_mars.insert(9,"Des fleurs de mars ne tient pas compte, non plus que des filles sans honte.");
	data_mars.insert(10,"Des fleurs que mars verra, peu de fruits on mangera.");
	data_mars.insert(11,"Des fleurs qui s'ouvrent en mars, on n'a que le regard.");
	data_mars.insert(12,"En février, civelles, en mars, bonnes et belles, En avril, fi d'elles.");
	data_mars.insert(13,"En mars, autant de gelées, en avril autant de poussées.");
	data_mars.insert(14,"En mars, firmament très éloigné, changement de temps peu éloigné. ");
	data_mars.insert(15,"En mars les vaches au pré , si ce n'est pour manger, c'est pour s'y gratter.");
	data_mars.insert(16,"En mars, manteau de neige dans les près, manteau de foin prochain été");
	data_mars.insert(17,"En mars, quand il fait beau, prends ton manteau.");
	data_mars.insert(18,"En mars, quand il tonne chacun s'en étonne.");
	data_mars.insert(19,"En mars, quand le merle a sifflé, l'hiver s'en est allé");
	data_mars.insert(20,"En mars, vent ou pluie, que chacun veille sur lui.");
	data_mars.insert(21,"Entre mars et avril, on sait si le coucou est mort ou en vie.");
	data_mars.insert(22,"février et mars trop chauds, mettent le printemps au tombeau.");
	data_mars.insert(23,"février remplit les fossés, c'est à mars de les assécher.");
	data_mars.insert(24,"février remplit les fossés, mars les vide.");
	data_mars.insert(25,"Fleur marsière ne tient guère.");
	data_mars.insert(26,"Hâle de mars, pluie d'avril, rosée de mai, font d'août et septembre les plus beaux mois de l'année.");
	data_mars.insert(27,"La vigne dit : En mars me lie, en mars me taille, en mars il faut qu'on me travaille.");
	data_mars.insert(28,"Le bourgeon de mars rempli les chars, celui d'avril le baril, celui de mai le chai.");
	data_mars.insert(29,"Le soleil de mars, donne des rhumes tenaces.");
	data_mars.insert(30,"Malgré le mauvais temps, mars prépare en secret le printemps.");
	data_mars.insert(31,"mars avec ses marteaux, dans leur mère tue leur veaux.");
	data.insert(3, data_mars);
	QMap<int, QString> data_avril;
	data_avril.insert(1," Pluie de Saint-Hugues à Sainte-Sophie, Remplit granges et fournils.");
	data_avril.insert(2," Au moment où  commence avril, L'esprit doit se montrer subtil");
	data_avril.insert(3," Comme il fait le trois, Il fait le mois.");
	data_avril.insert(4," Si les quatre premiers jours d'avril sont venteux il y en aura pour quarante jours.");
	data_avril.insert(5," A la Sainte-Irène s'il fait beau, Il y aura moins de vin que d'eau.");
	data_avril.insert(6," Au jour de Saint-Prudence, S'il fait du vent, les moutons dansent.");
	data_avril.insert(7," Au sept d'avril, après le coucou, c'est le rossignol qui chante.");
	data_avril.insert(8," S'il pleut à l'Annonciation, Pluie en août à foison.");
	data_avril.insert(9," A la Sainte-Marie, toutes les aubépines sont fleuries.");
	data_avril.insert(10," Quand avril est froid et pluvieux, Les moissons n'en vont que mieux.");
	data_avril.insert(11," avril fait la fleur, mai en a l'honneur.");
	data_avril.insert(12," A Saint-Jules, les sansonnets tiennent ménages dans les clochers.");
	data_avril.insert(13," avril frais et mai chaud, Remplissent les granges jusqu'en haut.");
	data_avril.insert(14," Lorsqu'arrive la Saint-Valérien, l'arbre bourgeonne et les fruits ne sont plus loin.");
	data_avril.insert(15," Quand de Saint-Paterne vient la saison, la chaleur vient pour de bon.");
	data_avril.insert(16," Saint-Druon pluvieux, an fromenteux.");
	data_avril.insert(17," avril froid, pain et vin donne, mai froid les moissonne.");
	data_avril.insert(18," Lune d'avril Ne passe pas sans gelée.");
	data_avril.insert(19," A Sainte-léonide, Chaque blé pousse rapide.");
	data_avril.insert(20," A Sainte Théodore, Fleurit chaque bouton d'or.");
	data_avril.insert(21," A Saint-Anselme, Dernières fleurs sème.");
	data_avril.insert(22," Pluie le jour de Sainte-Opportune, Ni cerises, ni prunes.");
	data_avril.insert(23," Quand il pleut le jour de Saint-Georges, Sur cent cerises, on a quatorze.");
	data_avril.insert(24," avril a trente jours. Si trente et un il avait, Personne ne s'en plaindrait.");
	data_avril.insert(25," Entre Georges et Marquet, un jour de l'hiver se met.");
	data_avril.insert(26," Saint-Clet ferme la porte aux derniers pois.");
	data_avril.insert(27," A la Sainte-Zita, Le froid ne dure pas.");
	data_avril.insert(28," A Saint-Aimé, point de moutons affamés.");
	data_avril.insert(29," Caprices d'avril font tomber les fleurs, Et trembler les laboureurs.");
	data_avril.insert(30," A la Saint-Robert Tout arbre est vert.");
	data.insert(4, data_avril);
	QMap<int, QString> data_mai;
	data_mai.insert(1," De la pluie le premier jour de mai, Ote aux fourrages de la qualité");
	data_mai.insert(2," Au jour de la Saint-Boris, par malheur, c'est un mauvais vendangeur.");
	data_mai.insert(3," Qui n'a pas semé à la Sainte-Croix, Au lieu d'un grain en mettra trois.");
	data_mai.insert(4," mai fait ou défait.");
	data_mai.insert(5," Sainte Judith voit pinson au nid.");
	data_mai.insert(6," S'il fait beau à la petite Saint-Jean, année fructueuse en froment.");
	data_mai.insert(7," mai frileux: an langoureux. mai fleuri: an réjoui. mai venteux: an douteux.");
	data_mai.insert(8," Au mois de mai il faudrait qu'il ne plût jamais.");
	data_mai.insert(9," Rosée de mai, fait tout beau ou tout laid.");
	data_mai.insert(10," C'est à la Saint-Antonin, Que vend son vin le malin.");
	data_mai.insert(11," Attention, le premier des saints de glace, souvent tu en gardes la trace.");
	data_mai.insert(12," Les trois saints au sang de navet, Pancrace, Mamert et Servais, Sont bien nommés les saints de glace, Mamert, Servais et Pancrace.");
	data_mai.insert(13," Avant Saint-Servais, point d'été, après Saint-Servais, plus de gelée.");
	data_mai.insert(14," Saint-Boniface nous ôte la boue, Ou il nous en met jusqu'au cou.");
	data_mai.insert(15," A la Sainte-Denise, Finie la bise.");
	data_mai.insert(16," A la Saint-Honoré, S'il fait gelée, Le vin diminue de moitié");
	data_mai.insert(17," S'il tonne au jour de Saint-Pascal, Sans grêle, ce n'est pas un mal.");
	data_mai.insert(18," Bon fermier, à Sainte-Juliette, doit vendre ses poulettes.");
	data_mai.insert(19," Craignez le petit Yvonnet, le pire de tous quand il s'y met.");
	data_mai.insert(20," A Saint-Gobain, le bois prend feuilles, La futaie pousse à vue d'oeil.");
	data_mai.insert(21," Si elle gèle, Sainte-Quitère emporte tout dans son grand tablier.");
	data_mai.insert(22," En mai, Fleurit le hêtre et chante le geai.");
	data_mai.insert(23," Saint-Didier ramasse tout dans son devantier.");
	data_mai.insert(24," après Sainte-Angèle, le jardinier ne craint plus le gel.");
	data_mai.insert(25," S'il pleut à la Saint-Urbain, C'est quarante jours de pluie en chemin.");
	data_mai.insert(26," Quand il pleut à la Saint-Philippe, Le pauvre n'a pas besoin du riche.");
	data_mai.insert(27," A la Saint-Hildevert, Est mort tout arbre qui n'est pas vert.");
	data_mai.insert(28," Soleil de Saint-Germain, Nous promet du bon vin.");
	data_mai.insert(29," Celui qui s'allége avant le mois de mai, Certainement ne sait pas ce qu'il fait.");
	data_mai.insert(30," Lorsque mai est trop jardinier, cela ne remplit pas le grenier.");
	data_mai.insert(31," S'il pleut le jour de Sainte-Pétronille, le blé diminue jusqu'à la faucille.");
	data.insert(5, data_mai);
	QMap<int, QString> data_juin;
	data_juin.insert(1," A la Saint-Fortuné, grande hannetonnée.");
	data_juin.insert(2," A la Saint-Pothin, bonhomme, sême ton sarrasin.");
	data_juin.insert(3," A la Sainte-Clotilde, de fleur en buisson, Abeille butine à foison.");
	data_juin.insert(4," En juin, brume obscure, Trois jours seulement dure.");
	data_juin.insert(5," Prépare autant de tonneaux qu'en juin tu compteras de beaux jours.");
	data_juin.insert(6," Les bains que prend Saint-Norbert, Inondent toute la terre.");
	data_juin.insert(7," En juin trop de pluie et le grenier vide s'ennuie.");
	data_juin.insert(8," Saint-mars mouillé au petit jour, C'est de la pluie pour tout le jour.");
	data_juin.insert(9," A Saint-Félicien, mouche à miel n'a plus de bien.");
	data_juin.insert(10," A la Saint-Landry, s'il tonne restera vide la tonne.");
	data_juin.insert(11," Le soleil de Saint-Barnabé, à Saint-Médard casse le nez.");
	data_juin.insert(12," Qui naît à la Saint-Basilide ne sera jamais invalide.");
	data_juin.insert(13," Qui sème sa salade à Saint-Antoine en a comme la barbe d'un moine.");
	data_juin.insert(14," A Saint-Rufin, Cerises à plein jardin.");
	data_juin.insert(15," Pluie de Saint-Guy, c'est tout l'an qui rit.");
	data_juin.insert(16," Pluie de Saint-Aurélien, Belle avoine et mauvais foin.");
	data_juin.insert(17," S'il pleut à la Saint-François-Régis, le vin diminue jusqu'à la lie.");
	data_juin.insert(18," Pluie de Saint-léonce pour trente jours s'annonce.");
	data_juin.insert(19," Saint-Gervais, quand il est beau, Tire Médard et Barnabé de l'eau.");
	data_juin.insert(20," Pluie d'orage à la Saint-Sylvère, C'est beaucoup de vin dans le verre.");
	data_juin.insert(21," Pleurs de femmes et pluies d'été gros ruisseaux n'ont jamais fait.");
	data_juin.insert(22," A la Saint-Alban, On peut poser ses vêtements.");
	data_juin.insert(23," Qui pêche en juin, pêche fretin.");
	data_juin.insert(24," Pluie de Saint-Jean noie les noisettes, mais beau temps de Saint-Pierre les rachète.");
	data_juin.insert(25," S'il fait beau à la Saint-Guillaume, auras du blé plus que de chaume.");
	data_juin.insert(26," En juin trop de pluie, et le jardinier s'ennuie.");
	data_juin.insert(27," S'il pleut en juin, le jardinier ronge son poing.");
	data_juin.insert(28," A la Saint-Fabien, bon foin jaunit bien.");
	data_juin.insert(29," Saint-Pierre et Paul pluvieux, Est pour trente jours dangereux.");
	data_juin.insert(30," Lorsqu'en juin on voit sa fin, Saint-Martial souvent lave le chemin.");
	data.insert(6, data_juin);
	QMap<int, QString> data_juillet;
	data_juillet.insert(1,"Au mois de juillet, bouche noire, gosier sec.");
	data_juillet.insert(2,"Au mois de juillet, ni veste, ni corset");
	data_juillet.insert(3,"Au mois de juillet, on met la faux au sillon");
	data_juillet.insert(4,"Au mois de juin et de juillet, qui se marie, fort peu fait.");
	data_juillet.insert(5,"avril, quelques nids, mai, ils sont tous faits, juin, ils sont biens communs, juillet, ils sont tous cueillis.");
	data_juillet.insert(6,"Ciel de juillet rouge au matin, veut un pluvieux voisin.");
	data_juillet.insert(7,"De juillet, la chaleur fait de septembre la valeur");
	data_juillet.insert(8,"En juillet, faucille au poignet");
	data_juillet.insert(9,"En juillet jusqu'au dernier mets ton blé dans le grenier");
	data_juillet.insert(10,"En juillet mois d'abondance, le pauvre a toujours sa pitance.");
	data_juillet.insert(11,"En juillet pluie du matin est bonne au grain.");
	data_juillet.insert(12,"En juin, juillet et août, ni femme (ou ni huitres) ni choux.");
	data_juillet.insert(13,"En mi-juillet, pluie ou vent font mal au froment");
	data_juillet.insert(14,"Entre juillet et août, le boire est de bon goût.");
	data_juillet.insert(15,"Frais juillet épaisse tourte, met peu de vin dans la coupe");
	data_juillet.insert(16,"juillet, c'est le mois de la moisson, vite on dépouille les sillons");
	data_juillet.insert(17,"juillet doit rôtir ce que septembre mûrira.");
	data_juillet.insert(18,"Jamais en juillet sècheresse n'a causé la moindre tristesse");
	data_juillet.insert(19,"juillet ensoleillé remplit cave et grenier.");
	data_juillet.insert(20,"juillet et août, ni femmes ni choux");
	data_juillet.insert(21,"juillet, orage de nuit, peu de mal, mais que de bruit !");
	data_juillet.insert(22,"juillet sans orage, famine au village.");
	data_juillet.insert(23,"Les abeilles en juillet ne valent grain de millet.");
	data_juillet.insert(24,"mai, juin, juillet, bouche fraîche, le reste net.");
	data_juillet.insert(25,"Ne vous plaignez pas s'il tonne en juillet ; car en ce mois s'il ne tonnait, guerre et famine il y aurait.");
	data_juillet.insert(26,"On ne sait si juillet est bon qu'après - Faîtes la moisson");
	data_juillet.insert(27,"Petite pluie du matin en juillet est bonne pour le vin");
	data_juillet.insert(28,"Pluie de juillet, eau en janvier.");
	data_juillet.insert(29,"Pluie du matin, en juillet est bonne au vin");
	data_juillet.insert(30,"Pour avoir un beau navet, juillet doit le trouver fait.");
	data_juillet.insert(31,"Quand juillet commencera, ta faux affûteras");
	data.insert(7, data_juillet);
	QMap<int, QString> data_aout;
	data_aout.insert(1,"A la mi-août, les noix ont le ventre roux.");
	data_aout.insert(2,"A la mi-août, l'hiver se noue.");
	data_aout.insert(3,"août couve, septembre fait naître");
	data_aout.insert(4,"août mûrit les fruits, septembre les cueille.");
	data_aout.insert(5,"août mûrit, septembre vendange, en ces deux mois, tout bien s'arrange.");
	data_aout.insert(6,"août pluvieux, celliers vineux.");
	data_aout.insert(7,"août sans pluie fait maigrir la vache");
	data_aout.insert(8,"Au mois d'août, femmes retirez-vous.");
	data_aout.insert(9,"Au mois d'août il fait bon aller chercher salade au jardin");
	data_aout.insert(10,"Au mois d'août, le vent est fou.");
	data_aout.insert(11,"Au mois d'août, n'ôte ta flanelle qu'en cas de chaleur torrentielle !");
	data_aout.insert(12,"Ce que le mois d'août ne mûrira pas, ce n'est pas septembre qui le fera.");
	data_aout.insert(13,"C'est le mois d'août qui donne bon goût");
	data_aout.insert(14,"Chaleur d'août, c'est du bien partout");
	data_aout.insert(15,"Coupe ton bois en pleine lune d'août, il sera sain comme un os");
	data_aout.insert(16,"Dieu nous garde de la fange d'août, et de la poussière de mai.");
	data_aout.insert(17,"En août et en vendanges (ou : comme aux vendanges), il y a ni fêtes, ni dimanches.");
	data_aout.insert(18,"En août, il fait bon aller chercher salade et ciboule");
	data_aout.insert(19,"En août, les gélines sont sourdes (car ce mois là, les poules sont silencieuses).");
	data_aout.insert(20,"En août, le vent est fou");
	data_aout.insert(21,"En août, quiconque dormira sur midi s'en repentira");
	data_aout.insert(22,"En mai la boue, épis en août");
	data_aout.insert(23,"En novembre fou engendre, en août gît sa femme.");
	data_aout.insert(24,"Entre juillet et août, le boire est de bon goût.");
	data_aout.insert(25,"Il faut cueillir les choux, l'un des trois premier jours d'août.");
	data_aout.insert(26,"Jamais d'août la sécheresse n'amènera la richesse");
	data_aout.insert(27,"juillet et août, ni femmes ni choux");
	data_aout.insert(28,"Les deux Notre-Dame : Pèriode qui va du 15 août (Assomption) au 4 sept. (Nativité) :");
	data_aout.insert(29,"Les oeufs pondus entre les deux Notre-Dame, se gardent plus longtemps que les autres.");
	data_aout.insert(30,"Pluie de Notre-Dame, fait tout vin ou tout châtaigne.");
	data_aout.insert(31,"Entre les deux Notre-Dame, jamais serpent n'a osé se montrer");
	data.insert(8, data_aout);
	QMap<int, QString> data_septembre;
	data_septembre.insert(1,"août mûrit, septembre vendange, en ces deux mois, tout bien s'arrange.");
	data_septembre.insert(2,"Au mois de septembre, le feignant peut aller se pendre");
	data_septembre.insert(3,"Beau septembre emplira les chambres");
	data_septembre.insert(4,"Ce que le mois d'août ne mûrira pas, ce n'est pas septembre qui le fera.");
	data_septembre.insert(5,"Du premier au 8, l'hirondelle fuit.");
	data_septembre.insert(6,"En septembre, il fait bon être tout le jour dans la campagne");
	data_septembre.insert(7,"En septembre, la bruine, est toujours bonne à la vigne.");
	data_septembre.insert(8,"En septembre, le raisin ou la figue pendent.");
	data_septembre.insert(9,"En septembre, les feignants peuvent s'aller pendre.");
	data_septembre.insert(10,"En septembre pluie fine est bonne pour la vigne");
	data_septembre.insert(11,"En septembre, quand tu entends la grive chanter, cherche la maison pour t'abriter ou du bois pour te chauffer");
	data_septembre.insert(12,"En septembre se coupe ce qui pend.");
	data_septembre.insert(13,"En septembre, si brume reste en haut, il pleuvra à seau");
	data_septembre.insert(14,"En septembre, s'il tonne, la vendange est bonne");
	data_septembre.insert(15,"En septembre si trois jours il tonne, c'est un nouveau bail pour l'automne.");
	data_septembre.insert(16,"En septembre si tu es prudent, achète grains et vêtements.");
	data_septembre.insert(17,"En septembre, sois prudent, achète bois et vêtement !");
	data_septembre.insert(18,"En septembre, tous les fruits valent le prendre");
	data_septembre.insert(19,"Etoiles filantes en septembre, tonneaux petits en novembre");
	data_septembre.insert(20,"juillet doit rôtir ce que septembre mûrira");
	data_septembre.insert(21,"Le coq, en septembre, chantant la matinée, annonce une abondante rosée.");
	data_septembre.insert(22,"Nuées de septembre, pluie de novembre, gel en décembre");
	data_septembre.insert(23,"Orages de septembre, Neige en décembre");
	data_septembre.insert(24,"Pluie de septembre est bonne à semailles et à vigne");
	data_septembre.insert(25,"Pluie de septembre, joie du paysan");
	data_septembre.insert(26,"Pour vendanger il faut attendre au moins la fin de septembre.");
	data_septembre.insert(27,"Quand août n'est pas pluvieux, septembre est souvent radieux");
	data_septembre.insert(28,"Quand beaucoup d'étoiles filent en septembre, les tonneaux sont trop petits en novembre");
	data_septembre.insert(29,"Qu'en septembre il tonne, la vendange est bonne");
	data_septembre.insert(30,"septembre emporte les ponts ou tarit les fontaines (ou septembre emporte les ponts ou tarit les fonts)");
	data.insert(9, data_septembre);
	QMap<int, QString> data_octobre;
	data_octobre.insert(1,"Beaucoup de pluie en octobre, beaucoup de vent en décembre.");
	data_octobre.insert(2,"Bise à la Saint-Michel (29/09), octobre sec.");
	data_octobre.insert(3,"Brouillards d'octobre et pluvieux novembre (ou : pluie de novembre) font bon décembre.");
	data_octobre.insert(4,"Brouillard d'octobre, pluie de novembre, beaucoup de biens du ciel font descendre.");
	data_octobre.insert(5,"Brumes d'octobre et pluvieux novembre font ensemble un bon décembre");
	data_octobre.insert(6,"En octobre, brume passe, beau temps passe.");
	data_octobre.insert(7,"En octobre, il faut que l'homme vite s'habille quand le mûrier se déshabille.");
	data_octobre.insert(8,"En octobre, mieux vaut faire le feu que labourer par temps mou.");
	data_octobre.insert(9,"En octobre, qui n'a pas de manteau doit en trouver un bientôt.");
	data_octobre.insert(10,"En octobre, qui ne fume rien ne récolte rien.");
	data_octobre.insert(11,"En octobre, s'il tonne c'est la nouvelle bonne");
	data_octobre.insert(12,"En octobre, si tu es prudent, achète grains et vêtements");
	data_octobre.insert(13,"En octobre tonnerre, vendanges prospères.");
	data_octobre.insert(14,"Froid d'octobre tue les chenilles.");
	data_octobre.insert(15,"Gelée d'octobre rend le vigneron sobre.");
	data_octobre.insert(16,"octobre à moitié pluvieux rend le labour joyeux.");
	data_octobre.insert(17,"octobre à moitié pluvieux rend le laboureur joyeux, mais le vendangeur soucieux met de coté son vin vieux.");
	data_octobre.insert(18,"octobre en bruine, hiver en ruine.");
	data_octobre.insert(19,"octobre en brumes, mois à rhumes.");
	data_octobre.insert(20,"octobre ensoleillé, décembre emmitouflé");
	data_octobre.insert(21,"octobre est bon, s'il est de saison");
	data_octobre.insert(22,"octobre glacé, fait vermine trépasser.");
	data_octobre.insert(23,"octobre le vaillant surmène le paysan (ou : octobre le vaillant, fatigue son paysan)");
	data_octobre.insert(24,"octobre n'est jamais passé sans qu'il y ait cidre brassé");
	data_octobre.insert(25,"Pluie abondante pendant l'automne annonce printemps sec. (dicton breton)");
	data_octobre.insert(26,"Quand le vent est au nord le jour de la Saint-Michel (29/09), le mois d'octobre est au sec.");
	data_octobre.insert(27,"Quand octobre prend sa fin, dans la cuve est le raisin.");
	data_octobre.insert(28,"Quand d'octobre vient la fin, Toussaint est au matin.");
	data_octobre.insert(29,"S'il neige en octobre, l'Hiver sera sobre.");
	data_octobre.insert(30,"Si octobre s'emplit de vent, du froid tu patiras longtemps.");
	data_octobre.insert(31,"Tonnerre en octobre, vendanges peu sobres.");
	data.insert(10, data_octobre);
	QMap<int, QString> data_novembre;
	data_novembre.insert(1,"A la mi-novembre passée, il peut venter et neiger");
	data_novembre.insert(2,"Brouillards d'octobre et pluvieux novembre, font bon décembre.");
	data_novembre.insert(3,"Brouillard d'octobre, pluie de novembre, beaucoup de biens du ciel font descendre.");
	data_novembre.insert(4,"Brouillard en novembre, l'hiver sera tendre.");
	data_novembre.insert(5,"Brumes d'octobre et pluvieux novembre font ensemble un bon décembre");
	data_novembre.insert(6,"Chaleur en novembre (ou de la chaleur) cause de bien des gens la mort (ou encore : Chaleur de novembre nuit fort et provoque de bien des gens la mort)");
	data_novembre.insert(7,"En novembre, bon paysan va vendre son poulain.");
	data_novembre.insert(8,"En novembre fou engendre, en août gît sa femme.");
	data_novembre.insert(9,"En novembre, si la première neige ne prend pas, de l'Hiver elle ne prendra.");
	data_novembre.insert(10,"Etoiles filantes en septembre, tonneaux petits en novembre");
	data_novembre.insert(11,"Le mois des brumes (novembre) réchauffe par-devant et refroidit par-derrière.");
	data_novembre.insert(12,"Le mois de novembre est malsain, il fait tousser dés la Toussaint.");
	data_novembre.insert(13,"Le vent de novembre arrache la dernière feuille.");
	data_novembre.insert(14,"novembre, mois des brumes, réchauffe par-devant et refroidit par-derrière.");
	data_novembre.insert(15,"novembre, mois mort, vêts-toi plus fort ! (ou : novembre est le mois des morts, si tu ne veux pas mourir encore, habille-toi plus fort !)");
	data_novembre.insert(16,"Nuées de septembre, pluie de novembre, gel en décembre");
	data_novembre.insert(17,"Quand il tonne entre Toussaint et Noël, l'Hiver est en retard.");
	data_novembre.insert(18,"Quand l'eau sort au mois mort (novembre), toute l'année, elle sort.");
	data_novembre.insert(19,"Quand en novembre il a tonné, l'Hiver est avorté");
	data_novembre.insert(20,"Quand novembre aura fleurs nouvelles, morte saison sera cruelle.");
	data_novembre.insert(21,"Quelque temps qu'il fasse en novembre, commence le feu dans ta chambre !");
	data_novembre.insert(22,"Tonnerre de novembre remplit le grenier");
	data_novembre.insert(23,"Vent de novembre est mauvais sur l'eau.");
	data_novembre.insert(24,"En novembre, bon paysan va vendre son poulain.");
	data_novembre.insert(25,"En novembre fou engendre, en août gît sa femme.");
	data_novembre.insert(26,"En novembre, si la première neige ne prend pas, de l'Hiver elle ne prendra.");
	data_novembre.insert(27,"Etoiles filantes en septembre, tonneaux petits en novembre");
	data_novembre.insert(28,"Le mois des brumes (novembre) réchauffe par-devant et refroidit par-derrière.");
	data_novembre.insert(29,"Le mois de novembre est malsain, il fait tousser dés laToussaint.");
	data_novembre.insert(30,"Le vent de novembre arrache la dernière feuille.");
	data.insert(11, data_novembre);
	QMap<int, QString> data_decembre;
	data_decembre.insert(2,"Au temps de l'Avent, les coqs chantent par tous les temps.");
	data_decembre.insert(3,"Avents fleuris, abondance de fruits.");
	data_decembre.insert(4,"Beaucoup de pluie en octobre, beaucoup de vent en décembre.");
	data_decembre.insert(5,"Brouillards d'octobre et pluvieux novembre (ou pluie de novembre), font bon décembre.");
	data_decembre.insert(6,"Brouillard d'octobre, pluie de novembre, beaucoup de biens du ciel font décembre.");
	data_decembre.insert(7,"Brumes d'octobre et pluvieux novembre font ensemble un bon décembre");
	data_decembre.insert(8,"Chaque chose en son temps, les navets et les choux pour le mois de l'Avent.");
	data_decembre.insert(9,"Dans l'Avent, le temps chaud remplit caves et tonneaux");
	data_decembre.insert(10,"décembre aux pieds blancs s'en vient, an de neige et an de bien.");
	data_decembre.insert(11,"décembre de froid trop chiche, ne fait pas le paysan riche.");
	data_decembre.insert(12,"décembre prend, il ne rend (ou : et ne rend)");
	data_decembre.insert(13,"décembre trop beau, Eté dans l'eau.");
	data_decembre.insert(14,"De la Toussaint à la fin de l'Avent, jamais trop de puie ou de vent");
	data_decembre.insert(15,"En décembre, fait du bois et endors toi.");
	data_decembre.insert(16,"décembre froid, si la neige abonde en une année féconde, le laboureur a foi.");
	data_decembre.insert(17,"En décembre, journée courte, longue nuit ; l'abeille se tait, le jonc gémit.");
	data_decembre.insert(18,"En décembre, les pieds dans la cendre.");
	data_decembre.insert(19,"En décembre, pour que l'année aille comme il se doit, il convient que les champs s'enneigent par deux fois.");
	data_decembre.insert(20,"En décembre, quand le jour croît, aussi fait le froid.");
	data_decembre.insert(21,"Froid et neige de décembre, du blé à revendre.");
	data_decembre.insert(22,"Il fait bon semer dans les Avents, mais il ne faut pas le dire aux enfants.");
	data_decembre.insert(23,"Il faut les Avents froids et secs, si l'on veut boire sec.");
	data_decembre.insert(24,"La neige des Avents, a de longues dents.");
	data_decembre.insert(25,"La neige de l'Avent, gèle très facilement.");
	data_decembre.insert(26,"Le mois de l'Avent est de pluie et de vent, tire ton bonner jusqu'aux dents");
	data_decembre.insert(27,"Le tonnerre en décembre annonce pour l'an qui vient aux bêtes et aux gens abondance de biens.");
	data_decembre.insert(28,"Neige de décembre est engrais pour la terre.");
	data_decembre.insert(29,"Nuées de septembre, pluie de novembre, gel en décembre");
	data_decembre.insert(30,"octobre ensoleillé, décembre emmitouflé");
	data_decembre.insert(31,"Orages de septembre, Neige en décembre");
	data.insert(12, data_decembre);
}
